package main

import (
	"bytes"
	"context"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/jyang234/verdi/internal/align"
	"github.com/jyang234/verdi/internal/artifact"
	"github.com/jyang234/verdi/internal/evidence"
	"github.com/jyang234/verdi/internal/storyresolve"
)

// buildDispositionFixture renders a minimal, schema-valid deviation-report.md
// via the REAL renderer (align.RenderBody/RenderMarkdown — never a hand-typed
// markdown string), so every fixture this file builds is guaranteed
// byte-consistent with what `verdi align` itself would have produced, and
// self-validates before handing it back (never build a fixture that isn't
// itself a legal report).
func buildDispositionFixture(t *testing.T, findings []artifact.Finding, frozen *artifact.Frozen) []byte {
	t.Helper()
	return buildDispositionFixtureWithNotResurfaced(t, findings, nil, frozen)
}

// buildDispositionFixtureWithNotResurfaced is buildDispositionFixture's
// spec/finding-identity twin: a not-resurfaced: section rides alongside
// findings:, the shape a live candidate's backing record needs
// (TestRunDisposition_ConfirmsCandidate_* below).
func buildDispositionFixtureWithNotResurfaced(t *testing.T, findings, notResurfaced []artifact.Finding, frozen *artifact.Frozen) []byte {
	t.Helper()
	fm := &artifact.DeviationFrontmatter{
		Schema:        "verdi.deviation/v1",
		Covers:        "1111111111111111111111111111111111111111",
		Findings:      findings,
		NotResurfaced: notResurfaced,
		Digest:        "sha256:" + strings.Repeat("0", 64),
		Frozen:        frozen,
	}
	if err := fm.Validate(); err != nil {
		t.Fatalf("test setup: fixture frontmatter invalid: %v", err)
	}
	body := align.RenderBody(findings, nil, notResurfaced, nil, nil, nil)
	return align.RenderMarkdown(fm, body)
}

// writeDispositionStoreRoot builds a plain, non-git store root — `verdi
// disposition` never touches git or the judge (spec/disposition-verb dc-5:
// "a pure, local, offline read-mutate-write") — containing verdi.yaml and a
// single deviation-report.md at
// .verdi/specs/active/<specName>/deviation-report.md.
func writeDispositionStoreRoot(t *testing.T, specName string, reportMD []byte) string {
	t.Helper()
	root := t.TempDir()
	writeTestFile(t, filepath.Join(root, ".verdi", "verdi.yaml"), []byte("schema: verdi.layout/v1\n"))
	writeTestFile(t, reportPathFor(root, specName), reportMD)
	return root
}

func writeTestFile(t *testing.T, path string, content []byte) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir for %s: %v", path, err)
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func reportPathFor(root, specName string) string {
	return filepath.Join(root, ".verdi", "specs", "active", specName, "deviation-report.md")
}

func readFile(t *testing.T, path string) []byte {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}
	return data
}

func assertUnchanged(t *testing.T, path string, before []byte) {
	t.Helper()
	after := readFile(t, path)
	if !bytes.Equal(before, after) {
		t.Fatalf("%s was written to despite a refusal (no partial write allowed):\n--- before ---\n%s\n--- after ---\n%s", path, before, after)
	}
}

// runDispositionBinary execs the built verdi binary's "disposition" verb
// with args, cwd=dir, capturing stdout/stderr separately — driving the real
// binary, never cmdDisposition/runDisposition in-process (obligation
// disposition-verb--ac-1--behavioral / --ac-2--behavioral).
func runDispositionBinary(t *testing.T, bin, dir string, args ...string) (stdout, stderr string, code int) {
	t.Helper()
	cmd := exec.Command(bin, append([]string{"disposition"}, args...)...)
	cmd.Dir = dir
	var outBuf, errBuf bytes.Buffer
	cmd.Stdout = &outBuf
	cmd.Stderr = &errBuf
	err := cmd.Run()
	if err != nil {
		if ee, ok := err.(*exec.ExitError); ok {
			return outBuf.String(), errBuf.String(), ee.ExitCode()
		}
		t.Fatalf("running verdi disposition %v: %v", args, err)
	}
	return outBuf.String(), errBuf.String(), 0
}

// TestRunDisposition_RecordsInPlace_DigestAndIntegrityPreserved is
// obligation/disposition-verb--ac-1--behavioral: drives the built binary
// against a LIVING report generated by a real (non-freeze) `verdi align` run
// (buildAlignRepo + alignFakeJudgeOK, mirroring cmd/verdi/align_test.go's own
// harness — a genuine judge exchange, not a hand-typed fixture), then
// dispositions first the computed finding as `fixed` and then the judged
// finding as `accepted-deviation` (both decision values, sequentially, on the
// SAME report), proving each write: updates the target finding's frontmatter
// AND its rendered body bullet, leaves every OTHER finding byte-identical,
// and leaves digest/integrity byte-identical AND independently
// reverifiable — align.ComputeDigest recomputed from a fresh align.Compute
// over the same fixture tree still equals the stored digest, and
// align.VerifyIntegrity still succeeds against the genuine judge exchange.
//
// guide-claim: 8.1-align-deviation-disposition
func TestRunDisposition_RecordsInPlace_DigestAndIntegrityPreserved(t *testing.T) {
	bin := buildVerdiBinary(t)
	repo := buildAlignRepo(t)
	svcDir := filepath.Join(repo.Dir, "loansvc")
	reportPath := filepath.Join(repo.Dir, ".verdi", "specs", "active", "stale-decline", "deviation-report.md")

	deps := alignDeps{Runner: alignRunner(svcDir), JudgeCmd: alignFakeJudgeOK(t), ModelDigest: testResolveModelDigest(t, repo.Dir)}
	var out, errb bytes.Buffer
	if got := runAlign(context.Background(), repo.Dir, false, deps, &out, &errb); got != 0 {
		t.Fatalf("runAlign (setup) = %d, want 0; stderr=%s", got, errb.String())
	}

	spec, err := storyresolve.ResolveBuildSpec(repo.Dir, "feature/stale-decline")
	if err != nil {
		t.Fatalf("test setup: ResolveBuildSpec: %v", err)
	}

	verifyDigestAndIntegrity := func(t *testing.T, fm *artifact.DeviationFrontmatter) {
		t.Helper()
		computed, err := align.Compute(context.Background(), align.ComputedInput{Root: repo.Dir, Runner: alignRunner(svcDir), Spec: spec, Covers: fm.Covers})
		if err != nil {
			t.Fatalf("independent align.Compute: %v", err)
		}
		if err := align.VerifyDigest(fm, computed); err != nil {
			t.Fatalf("align.VerifyDigest: %v", err)
		}
		if err := align.VerifyIntegrity(fm); err != nil {
			t.Fatalf("align.VerifyIntegrity: %v", err)
		}
	}

	before := decodeReportFile(t, reportPath)
	verifyDigestAndIntegrity(t, before)

	judgedBefore, ok := findingByID(before.Findings, "judged-j-1")
	if !ok || judgedBefore.Dispositioned() {
		t.Fatalf("test setup: want an undispositioned judged finding j-1, got %+v (present=%v)", judgedBefore, ok)
	}
	var computedBefore artifact.Finding
	for _, f := range before.Findings {
		if f.Kind == artifact.FindingComputed {
			computedBefore = f
		}
	}
	if computedBefore.ID == "" || computedBefore.Dispositioned() {
		t.Fatalf("test setup: want an undispositioned computed finding, got %+v", computedBefore)
	}

	// Step 1: disposition the COMPUTED finding as `fixed`.
	_, stderr, code := runDispositionBinary(t, bin, repo.Dir, "spec/stale-decline", computedBefore.ID, "fixed", "--rationale", "regenerated boundary contract confirms the declared edge")
	if code != 0 {
		t.Fatalf("verdi disposition (computed, fixed) exit = %d, want 0; stderr=%s", code, stderr)
	}

	afterStep1 := decodeReportFile(t, reportPath)
	cf, ok := findingByID(afterStep1.Findings, computedBefore.ID)
	if !ok || cf.Disposition != artifact.FindingFixed || cf.Note != "regenerated boundary contract confirms the declared edge" {
		t.Fatalf("computed finding after step 1 = %+v, want disposition fixed with the given rationale", cf)
	}
	jf, ok := findingByID(afterStep1.Findings, "judged-j-1")
	if !ok || jf != judgedBefore {
		t.Fatalf("judged finding j-1 changed during step 1's unrelated write: before=%+v after=%+v", judgedBefore, jf)
	}
	if afterStep1.Digest != before.Digest || afterStep1.Integrity != before.Integrity {
		t.Fatalf("digest/integrity changed after step 1: before={digest:%s integrity:%s} after={digest:%s integrity:%s}",
			before.Digest, before.Integrity, afterStep1.Digest, afterStep1.Integrity)
	}
	verifyDigestAndIntegrity(t, afterStep1)

	step1Bytes := readFile(t, reportPath)
	if !bytes.Contains(step1Bytes, []byte(align.RenderFindingLine(cf))) {
		t.Fatalf("body does not contain the updated computed-finding bullet line; body:\n%s", step1Bytes)
	}

	// Step 2: disposition the JUDGED finding (j-1) as `accepted-deviation`.
	_, stderr2, code2 := runDispositionBinary(t, bin, repo.Dir, "spec/stale-decline", "judged-j-1", "accepted-deviation", "--rationale", "owner-ratified: intentional, tracked separately")
	if code2 != 0 {
		t.Fatalf("verdi disposition (judged, accepted-deviation) exit = %d, want 0; stderr=%s", code2, stderr2)
	}

	afterStep2 := decodeReportFile(t, reportPath)
	jf2, ok := findingByID(afterStep2.Findings, "judged-j-1")
	if !ok || jf2.Disposition != artifact.FindingAcceptedDeviation || jf2.Note != "owner-ratified: intentional, tracked separately" {
		t.Fatalf("judged finding after step 2 = %+v, want disposition accepted-deviation with the given rationale", jf2)
	}
	// The computed finding's step-1 write must survive step 2 untouched.
	cf2, ok := findingByID(afterStep2.Findings, computedBefore.ID)
	if !ok || cf2 != cf {
		t.Fatalf("computed finding changed during step 2's unrelated write: before=%+v after=%+v", cf, cf2)
	}
	if afterStep2.Digest != before.Digest || afterStep2.Integrity != before.Integrity {
		t.Fatalf("digest/integrity changed after step 2: before={digest:%s integrity:%s} after={digest:%s integrity:%s}",
			before.Digest, before.Integrity, afterStep2.Digest, afterStep2.Integrity)
	}
	verifyDigestAndIntegrity(t, afterStep2)

	step2Bytes := readFile(t, reportPath)
	if !bytes.Contains(step2Bytes, []byte(align.RenderFindingLine(jf2))) {
		t.Fatalf("body does not contain the updated judged-finding bullet line; body:\n%s", step2Bytes)
	}
	if bytes.Contains(step2Bytes, []byte(align.RenderFindingLine(judgedBefore))) {
		t.Fatalf("body still contains j-1's OLD (undispositioned) bullet line; body:\n%s", step2Bytes)
	}
}

// TestRunDisposition_SurvivesFreeze is obligation/disposition-verb--ac-3--behavioral
// (mirroring cmd/verdi/align_test.go's TestRunAlign_FreezePreservesDispositions,
// the same drifting-judge harness the T.1/D6-24 keep-genuine fix proved
// against): generates a living report via a real (non-freeze) `verdi align`
// run, dispositions EVERY finding using the BUILT `verdi disposition` binary
// — never by direct struct/file mutation — then runs `verdi align --freeze`
// with a judge that would produce DIFFERENT content on a hypothetical
// regeneration (alignFakeJudgeDrift). Proves align.FreezeInPlace fires: the
// frozen report's findings, dispositions, and notes are byte-identical to
// what the disposition verb wrote, and the drifting judge's content is
// nowhere in the frozen output.
func TestRunDisposition_SurvivesFreeze(t *testing.T) {
	bin := buildVerdiBinary(t)
	repo := buildAlignRepo(t)
	svcDir := filepath.Join(repo.Dir, "loansvc")
	reportPath := filepath.Join(repo.Dir, ".verdi", "specs", "active", "stale-decline", "deviation-report.md")

	living := alignDeps{Runner: alignRunner(svcDir), JudgeCmd: alignFakeJudgeOK(t), ModelDigest: testResolveModelDigest(t, repo.Dir)}
	var out, errb bytes.Buffer
	if got := runAlign(context.Background(), repo.Dir, false, living, &out, &errb); got != 0 {
		t.Fatalf("runAlign (living) = %d, want 0; stderr=%s", got, errb.String())
	}

	before := decodeReportFile(t, reportPath)
	if len(before.Findings) == 0 {
		t.Fatal("test setup: living report carries no findings to disposition")
	}

	// Disposition EVERY finding via the built binary — never by direct
	// struct/file mutation (the obligation's own bar).
	for _, f := range before.Findings {
		decision := artifact.FindingFixed
		rationale := "fixed by the build"
		if f.Kind == artifact.FindingJudged {
			decision = artifact.FindingAcceptedDeviation
			rationale = "owner-ratified: intentional, tracked separately"
		}
		_, stderr, code := runDispositionBinary(t, bin, repo.Dir, "spec/stale-decline", f.ID, string(decision), "--rationale", rationale)
		if code != 0 {
			t.Fatalf("verdi disposition %s: exit = %d, want 0; stderr=%s", f.ID, code, stderr)
		}
	}

	afterDispositioning := decodeReportFile(t, reportPath)
	if !artifact.AllDispositioned(afterDispositioning.Findings) {
		t.Fatalf("not every finding is dispositioned after driving the verb over all of them: %+v", afterDispositioning.Findings)
	}
	dispositioned := make(map[string]artifact.Finding, len(afterDispositioning.Findings))
	for _, f := range afterDispositioning.Findings {
		dispositioned[f.ID] = f
	}

	// Freeze — with a judge that now DRIFTS (different id + text). A
	// faithful freeze must ignore it and stamp the disposition-verb-adjudicated
	// living report as-is (align.FreezeInPlace, PR #99 + the D6-24/T.1
	// keep-genuine guard, PR #101).
	frozenDeps := alignDeps{Runner: alignRunner(svcDir), JudgeCmd: alignFakeJudgeDrift(t), ModelDigest: testResolveModelDigest(t, repo.Dir)}
	var out2, errb2 bytes.Buffer
	if got := runAlign(context.Background(), repo.Dir, true, frozenDeps, &out2, &errb2); got != 0 {
		t.Fatalf("runAlign (freeze) = %d, want 0; stderr=%s", got, errb2.String())
	}

	frozen := decodeReportFile(t, reportPath)
	if frozen.Frozen == nil {
		t.Fatal("frozen report carries no Frozen stamp")
	}
	if len(frozen.Findings) != len(dispositioned) {
		t.Fatalf("frozen report has %d findings, want %d (the disposition-verb-written set)", len(frozen.Findings), len(dispositioned))
	}
	for _, f := range frozen.Findings {
		want, ok := dispositioned[f.ID]
		if !ok {
			t.Fatalf("frozen finding %s was not among the disposition-verb-written set: %+v", f.ID, f)
		}
		if f != want {
			t.Fatalf("frozen finding %s = %+v, want the disposition-verb-written %+v (freeze must be verbatim)", f.ID, f, want)
		}
	}

	// The drifting judge's content must be nowhere in the frozen output —
	// proof that the D6-24 keep-genuine/freeze-in-place path fired rather
	// than a hypothetical re-judge leaking through.
	frozenBytes := readFile(t, reportPath)
	for _, driftSubstr := range []string{"j-drift", "a fresh, differently-worded semantic reading"} {
		if bytes.Contains(frozenBytes, []byte(driftSubstr)) {
			t.Fatalf("frozen report contains the drifting judge's content (%q) — freeze re-judged instead of preserving the disposition-verb-written report:\n%s", driftSubstr, frozenBytes)
		}
	}
}

// TestRunDisposition_JudgeNewlineTextRendersSingleLineAndDispositionsCleanly
// is ADJ-53's j-4 fix proof, end to end: a real (non-freeze) `verdi align`
// run against a judge whose finding text carries an embedded newline
// (alignFakeJudgeNewlineText, the same fixture shape as
// TestRunJudgeOnce_NewlineInTextIsNormalized's unit-level proof) must
// produce a report whose body renders that finding as exactly ONE line,
// and the finding must then disposition cleanly through the BUILT binary —
// the exact permanent-brick scenario judged-j-4 named, now closed at the
// source (internal/align/judge.go's normalizeJudgeText) rather than taught
// to the verb (ADJ-53's own chosen option).
func TestRunDisposition_JudgeNewlineTextRendersSingleLineAndDispositionsCleanly(t *testing.T) {
	bin := buildVerdiBinary(t)
	repo := buildAlignRepo(t)
	svcDir := filepath.Join(repo.Dir, "loansvc")
	reportPath := filepath.Join(repo.Dir, ".verdi", "specs", "active", "stale-decline", "deviation-report.md")

	deps := alignDeps{Runner: alignRunner(svcDir), JudgeCmd: alignFakeJudgeNewlineText(t), ModelDigest: testResolveModelDigest(t, repo.Dir)}
	var out, errb bytes.Buffer
	if got := runAlign(context.Background(), repo.Dir, false, deps, &out, &errb); got != 0 {
		t.Fatalf("runAlign (newline-text judge) = %d, want 0; stderr=%s", got, errb.String())
	}

	before := decodeReportFile(t, reportPath)
	jf, ok := findingByID(before.Findings, "judged-j-newline")
	if !ok {
		t.Fatalf("test setup: no judged-j-newline finding among %+v", before.Findings)
	}
	if strings.ContainsAny(jf.Text, "\n\r") {
		t.Fatalf("finding text = %q, contains a raw newline/CR — normalizeJudgeText should have stripped it at the align/judge seam", jf.Text)
	}
	if !strings.Contains(jf.Text, "line one") || !strings.Contains(jf.Text, "line two") {
		t.Fatalf("finding text = %q, want it to still carry both halves of the judge's text", jf.Text)
	}

	// The report's BODY must render this finding as exactly ONE whole
	// line — not merely "somewhere as a substring" (strings.Split on "\n"
	// is the same line-boundary-anchored check the verb's own
	// replaceWholeLine uses, ADJ-52's j-2 fix).
	wantLine := align.RenderFindingLine(jf)
	bodyLines := strings.Split(string(readFile(t, reportPath)), "\n")
	matches := 0
	for _, l := range bodyLines {
		if l == wantLine {
			matches++
		}
	}
	if matches != 1 {
		t.Fatalf("expected exactly one whole-line match for the finding's rendered line, found %d; body:\n%s", matches, readFile(t, reportPath))
	}

	// Disposition it — must succeed cleanly. Before ADJ-53's source fix,
	// this exact scenario permanently bricked (judged-j-4): the verb's
	// whole-line matcher could never match a multi-line "line" against any
	// single split-line element.
	_, stderr, code := runDispositionBinary(t, bin, repo.Dir, "spec/stale-decline", "judged-j-newline", "accepted-deviation", "--rationale", "confirmed normalized to a single line; dispositions cleanly")
	if code != 0 {
		t.Fatalf("verdi disposition (newline-text finding) exit = %d, want 0 (must disposition cleanly); stderr=%s", code, stderr)
	}

	after := decodeReportFile(t, reportPath)
	f, ok := findingByID(after.Findings, "judged-j-newline")
	if !ok || f.Disposition != artifact.FindingAcceptedDeviation || f.Note != "confirmed normalized to a single line; dispositions cleanly" {
		t.Fatalf("judged-j-newline = %+v, want disposition accepted-deviation with the given rationale", f)
	}
}

// TestRunDisposition_Refusals is obligation/disposition-verb--ac-2--behavioral:
// table-driven, driving the built binary against fixture stores, proving
// every named refusal is a verdict (exit 1) or operational error (exit 2) as
// ac-2 specifies, and that every refusal writes NOTHING (byte-identical
// report before/after) — while the one deliberate write path (--amend
// against an existing disposition) actually replaces it.
func TestRunDisposition_Refusals(t *testing.T) {
	bin := buildVerdiBinary(t)

	livingFindings := func() []artifact.Finding {
		return []artifact.Finding{
			{ID: "computed-a", Kind: artifact.FindingComputed, Text: "declared boundary holds"},
			{ID: "judged-b", Kind: artifact.FindingJudged, Text: "a judged reading", Disposition: artifact.FindingFixed, Note: "already handled"},
		}
	}

	t.Run("unknown finding id refuses and names it", func(t *testing.T) {
		root := writeDispositionStoreRoot(t, "demo", buildDispositionFixture(t, livingFindings(), nil))
		path := reportPathFor(root, "demo")
		before := readFile(t, path)

		_, stderr, code := runDispositionBinary(t, bin, root, "spec/demo", "no-such-finding", "fixed", "--rationale", "x")
		if code != 1 {
			t.Fatalf("exit = %d, want 1 (verdict); stderr=%s", code, stderr)
		}
		if !strings.Contains(stderr, "no-such-finding") {
			t.Fatalf("stderr = %q, want it to name the unknown finding id", stderr)
		}
		assertUnchanged(t, path, before)
	})

	t.Run("already dispositioned without --amend refuses and names it", func(t *testing.T) {
		root := writeDispositionStoreRoot(t, "demo", buildDispositionFixture(t, livingFindings(), nil))
		path := reportPathFor(root, "demo")
		before := readFile(t, path)

		_, stderr, code := runDispositionBinary(t, bin, root, "spec/demo", "judged-b", "accepted-deviation", "--rationale", "y")
		if code != 1 {
			t.Fatalf("exit = %d, want 1 (verdict); stderr=%s", code, stderr)
		}
		if !strings.Contains(stderr, "judged-b") {
			t.Fatalf("stderr = %q, want it to name the already-dispositioned finding", stderr)
		}
		assertUnchanged(t, path, before)
	})

	t.Run("amend replaces an existing disposition", func(t *testing.T) {
		root := writeDispositionStoreRoot(t, "demo", buildDispositionFixture(t, livingFindings(), nil))
		path := reportPathFor(root, "demo")

		_, stderr, code := runDispositionBinary(t, bin, root, "spec/demo", "judged-b", "accepted-deviation", "--rationale", "amended rationale", "--amend")
		if code != 0 {
			t.Fatalf("exit = %d, want 0; stderr=%s", code, stderr)
		}
		after := decodeReportFile(t, path)
		f, ok := findingByID(after.Findings, "judged-b")
		if !ok || f.Disposition != artifact.FindingAcceptedDeviation || f.Note != "amended rationale" {
			t.Fatalf("judged-b = %+v, want amended to accepted-deviation with the new rationale", f)
		}
		other, ok := findingByID(after.Findings, "computed-a")
		if !ok || other.Dispositioned() {
			t.Fatalf("computed-a changed during an unrelated amend: %+v", other)
		}
	})

	t.Run("amend with nothing to amend refuses and names it", func(t *testing.T) {
		root := writeDispositionStoreRoot(t, "demo", buildDispositionFixture(t, livingFindings(), nil))
		path := reportPathFor(root, "demo")
		before := readFile(t, path)

		_, stderr, code := runDispositionBinary(t, bin, root, "spec/demo", "computed-a", "fixed", "--rationale", "z", "--amend")
		if code != 1 {
			t.Fatalf("exit = %d, want 1 (verdict); stderr=%s", code, stderr)
		}
		if !strings.Contains(stderr, "computed-a") {
			t.Fatalf("stderr = %q, want it to name the finding with nothing to amend", stderr)
		}
		assertUnchanged(t, path, before)
	})

	t.Run("frozen report refuses unconditionally, including with --amend", func(t *testing.T) {
		frozen := &artifact.Frozen{At: "2024-01-01", Commit: "1111111111111111111111111111111111111111"}
		root := writeDispositionStoreRoot(t, "demo", buildDispositionFixture(t, livingFindings(), frozen))
		path := reportPathFor(root, "demo")
		before := readFile(t, path)

		_, stderr, code := runDispositionBinary(t, bin, root, "spec/demo", "computed-a", "fixed", "--rationale", "z")
		if code != 1 {
			t.Fatalf("exit = %d, want 1 (verdict); stderr=%s", code, stderr)
		}
		if !strings.Contains(stderr, "frozen") {
			t.Fatalf("stderr = %q, want it to name the report frozen", stderr)
		}
		assertUnchanged(t, path, before)

		_, stderr2, code2 := runDispositionBinary(t, bin, root, "spec/demo", "judged-b", "accepted-deviation", "--rationale", "z", "--amend")
		if code2 != 1 {
			t.Fatalf("--amend exit = %d, want 1 (verdict); stderr=%s", code2, stderr2)
		}
		if !strings.Contains(stderr2, "frozen") {
			t.Fatalf("--amend stderr = %q, want it to name the report frozen", stderr2)
		}
		assertUnchanged(t, path, before)
	})

	t.Run("body/frontmatter desync for a finding refuses as a verdict, never an internal error (ADJ-53 j-5)", func(t *testing.T) {
		findings := livingFindings()
		reportMD := buildDispositionFixture(t, findings, nil)

		// Corrupt the body: replace computed-a's genuine rendered line with
		// hand-drifted text bearing no relation to its frontmatter entry —
		// the exact "body hand-drifted from its frontmatter" scenario j-5
		// named. This is a condition of the REPORT'S OWN STATE (dc-3's
		// verdict class), never an operational failure; ADJ-53 reclassifies
		// it from exit 2 "internal error" to exit 1.
		oldLine := align.RenderFindingLine(findings[0])
		corrupted := bytes.Replace(reportMD, []byte(oldLine), []byte("- **computed-a** [UNDISPOSITIONED]: a hand-drifted line bearing no relation to the frontmatter"), 1)
		if bytes.Equal(corrupted, reportMD) {
			t.Fatal("test setup: expected computed-a's rendered line to be present and replaceable")
		}

		root := writeDispositionStoreRoot(t, "demo", corrupted)
		path := reportPathFor(root, "demo")
		before := readFile(t, path)

		_, stderr, code := runDispositionBinary(t, bin, root, "spec/demo", "computed-a", "fixed", "--rationale", "z")
		if code != 1 {
			t.Fatalf("exit = %d, want 1 (verdict — a body/frontmatter desync, ADJ-53's j-5 reclassification); stderr=%s", code, stderr)
		}
		if strings.Contains(stderr, "internal error") {
			t.Fatalf("stderr = %q, must NOT say 'internal error' — this misattributes an externally-authored report condition to a tool bug (ADJ-53)", stderr)
		}
		if !strings.Contains(stderr, "computed-a") || !strings.Contains(stderr, "drifted") {
			t.Fatalf("stderr = %q, want it to honestly name the finding and the drift", stderr)
		}
		assertUnchanged(t, path, before)
	})

	t.Run("missing deviation-report.md is an operational error", func(t *testing.T) {
		root := t.TempDir()
		writeTestFile(t, filepath.Join(root, ".verdi", "verdi.yaml"), []byte("schema: verdi.layout/v1\n"))

		_, stderr, code := runDispositionBinary(t, bin, root, "spec/nope", "computed-a", "fixed", "--rationale", "z")
		if code != 2 {
			t.Fatalf("exit = %d, want 2 (operational); stderr=%s", code, stderr)
		}
	})

	t.Run("malformed report fails strict decode as an operational error", func(t *testing.T) {
		root := writeDispositionStoreRoot(t, "demo", []byte("---\nschema: verdi.deviation/v1\nunknown_field: true\n---\nbody\n"))

		_, stderr, code := runDispositionBinary(t, bin, root, "spec/demo", "computed-a", "fixed", "--rationale", "z")
		if code != 2 {
			t.Fatalf("exit = %d, want 2 (operational); stderr=%s", code, stderr)
		}
	})

	t.Run("bad argument shapes are operational errors, never touching a report", func(t *testing.T) {
		cases := []struct {
			name string
			args []string
		}{
			{"no args", nil},
			{"missing --rationale", []string{"spec/demo", "computed-a", "fixed"}},
			{"unknown decision", []string{"spec/demo", "computed-a", "close-enough", "--rationale", "z"}},
			{"too many positionals", []string{"spec/demo", "computed-a", "fixed", "extra"}},
			{"rationale contains a newline", []string{"spec/demo", "computed-a", "fixed", "--rationale", "line one\nline two"}},
			{"rationale contains a control character", []string{"spec/demo", "computed-a", "fixed", "--rationale", "text\twith\ttab"}},
		}
		for _, tc := range cases {
			t.Run(tc.name, func(t *testing.T) {
				root := writeDispositionStoreRoot(t, "demo", buildDispositionFixture(t, livingFindings(), nil))
				path := reportPathFor(root, "demo")
				before := readFile(t, path)

				_, stderr, code := runDispositionBinary(t, bin, root, tc.args...)
				if code != 2 {
					t.Fatalf("exit = %d, want 2 (operational usage error); stderr=%s", code, stderr)
				}
				assertUnchanged(t, path, before)
			})
		}
	})
}

// TestRunDisposition_RationaleValidation is ADJ-52's j-3 fix proof: a
// --rationale carrying a newline or other control character refuses as a
// malformed invocation (exit 2), naming the single-line-bullet constraint
// (align.RenderFindingLine renders a disposition's rationale as one line of
// a markdown bullet; a newline would silently break that invariant with no
// prior argument-shape check catching it — the exact gap the judge found).
// A plain, punctuation-bearing, multi-word rationale must still work
// (exit 0) — the fix must not become an over-broad rejection.
func TestRunDisposition_RationaleValidation(t *testing.T) {
	bin := buildVerdiBinary(t)

	livingFindings := []artifact.Finding{
		{ID: "computed-a", Kind: artifact.FindingComputed, Text: "declared boundary holds"},
	}

	t.Run("newline refuses and names the single-line constraint", func(t *testing.T) {
		root := writeDispositionStoreRoot(t, "demo", buildDispositionFixture(t, livingFindings, nil))
		path := reportPathFor(root, "demo")
		before := readFile(t, path)

		_, stderr, code := runDispositionBinary(t, bin, root, "spec/demo", "computed-a", "fixed", "--rationale", "first line\nsecond line")
		if code != 2 {
			t.Fatalf("exit = %d, want 2 (operational usage error); stderr=%s", code, stderr)
		}
		if !strings.Contains(stderr, "control character") || !strings.Contains(stderr, "single-line") {
			t.Fatalf("stderr = %q, want it to name the control-character/single-line-bullet constraint", stderr)
		}
		assertUnchanged(t, path, before)
	})

	t.Run("a non-newline control character (tab) refuses the same way", func(t *testing.T) {
		root := writeDispositionStoreRoot(t, "demo", buildDispositionFixture(t, livingFindings, nil))
		path := reportPathFor(root, "demo")
		before := readFile(t, path)

		_, stderr, code := runDispositionBinary(t, bin, root, "spec/demo", "computed-a", "fixed", "--rationale", "has\ta\ttab")
		if code != 2 {
			t.Fatalf("exit = %d, want 2 (operational usage error); stderr=%s", code, stderr)
		}
		if !strings.Contains(stderr, "control character") {
			t.Fatalf("stderr = %q, want it to name the control-character constraint", stderr)
		}
		assertUnchanged(t, path, before)
	})

	t.Run("plain multi-word rationale with punctuation still works", func(t *testing.T) {
		root := writeDispositionStoreRoot(t, "demo", buildDispositionFixture(t, livingFindings, nil))
		path := reportPathFor(root, "demo")

		const rationale = "owner-ratified: intentional, tracked separately (see ADR-12) — no server-side change."
		_, stderr, code := runDispositionBinary(t, bin, root, "spec/demo", "computed-a", "fixed", "--rationale", rationale)
		if code != 0 {
			t.Fatalf("exit = %d, want 0 (plain rationale must still work); stderr=%s", code, stderr)
		}
		after := decodeReportFile(t, path)
		f, ok := findingByID(after.Findings, "computed-a")
		if !ok || f.Disposition != artifact.FindingFixed || f.Note != rationale {
			t.Fatalf("computed-a = %+v, want disposition fixed with the given plain rationale", f)
		}
	})
}

// TestRunDisposition_QuotingRationaleDoesNotBrickAnotherFinding is ADJ-52's
// j-2 fix proof: a rationale that quotes another finding's full rendered
// bullet verbatim must never make that OTHER finding's later disposition
// attempt refuse with a false "found N" internal error. Before the fix (a
// raw strings.Count substring lookup over the whole body), the quoted
// finding's line occurred twice in the body text — once as its own real,
// standalone line, once embedded inside the quoting finding's own line —
// permanently bricking the quoted finding's disposition with no sanctioned
// escape hatch, reachable purely through the verb's own documented inputs.
func TestRunDisposition_QuotingRationaleDoesNotBrickAnotherFinding(t *testing.T) {
	bin := buildVerdiBinary(t)

	findings := []artifact.Finding{
		{ID: "finding-a", Kind: artifact.FindingComputed, Text: "a's own claim"},
		{ID: "finding-b", Kind: artifact.FindingJudged, Text: "b's own claim"},
	}
	root := writeDispositionStoreRoot(t, "demo", buildDispositionFixture(t, findings, nil))
	path := reportPathFor(root, "demo")

	// finding-b's CURRENT (undispositioned) rendered line — the exact text
	// a rationale would need to quote verbatim to trigger the brick.
	quotedLine := align.RenderFindingLine(findings[1])

	// Disposition finding-a first, with a rationale that quotes finding-b's
	// full rendered bullet verbatim (embedded inside finding-a's own,
	// longer line — never finding-b's own standalone line).
	_, stderr, code := runDispositionBinary(t, bin, root, "spec/demo", "finding-a", "fixed", "--rationale", "see also: "+quotedLine)
	if code != 0 {
		t.Fatalf("verdi disposition (quoting rationale) exit = %d, want 0; stderr=%s", code, stderr)
	}

	// finding-b's own, still-undispositioned line must STILL be locatable
	// and dispositionable — the fix's whole proof (this would have exited 2
	// with "found 2" against the pre-fix substring-count lookup).
	_, stderr2, code2 := runDispositionBinary(t, bin, root, "spec/demo", "finding-b", "accepted-deviation", "--rationale", "unrelated rationale for b")
	if code2 != 0 {
		t.Fatalf("verdi disposition (finding-b, post-quoting) exit = %d, want 0 (must not brick on the embedded quote); stderr=%s", code2, stderr2)
	}

	after := decodeReportFile(t, path)
	fb, ok := findingByID(after.Findings, "finding-b")
	if !ok || fb.Disposition != artifact.FindingAcceptedDeviation || fb.Note != "unrelated rationale for b" {
		t.Fatalf("finding-b = %+v, want disposition accepted-deviation with the given rationale", fb)
	}
	fa, ok := findingByID(after.Findings, "finding-a")
	if !ok || fa.Disposition != artifact.FindingFixed {
		t.Fatalf("finding-a = %+v, want disposition fixed (unaffected by finding-b's later write)", fa)
	}
}

// TestRunDisposition_UsesAtomicWrite is ADJ-54's j-6 fix proof, structural:
// the write path must replace the report via rename-into-place (a NEW
// underlying file — os.SameFile false against the pre-write file), never a
// plain in-place truncate+write (which keeps the SAME underlying file,
// os.SameFile true) — the portable, observable signature of
// internal/atomicfile.Write's temp-then-rename convention, distinguishing
// it from the pre-fix os.WriteFile. atomicfile.Write's own fsync/crash-
// durability guarantees are already proven by internal/atomicfile's own
// test suite (TestWrite_Happy and neighbors); this proves THIS verb's
// write path actually calls it, closing the truncation risk judged-j-6
// named (a crash/kill/disk-full mid-write leaving a truncated, permanent
// record unrecoverable for content never committed to git).
func TestRunDisposition_UsesAtomicWrite(t *testing.T) {
	bin := buildVerdiBinary(t)
	root := writeDispositionStoreRoot(t, "demo", buildDispositionFixture(t, []artifact.Finding{
		{ID: "computed-a", Kind: artifact.FindingComputed, Text: "declared boundary holds"},
	}, nil))
	path := reportPathFor(root, "demo")

	before, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat before: %v", err)
	}

	_, stderr, code := runDispositionBinary(t, bin, root, "spec/demo", "computed-a", "fixed", "--rationale", "z")
	if code != 0 {
		t.Fatalf("verdi disposition: exit %d, want 0; stderr=%s", code, stderr)
	}

	after, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat after: %v", err)
	}
	if os.SameFile(before, after) {
		t.Fatal("report file identity unchanged across the write — want a NEW underlying file (rename-into-place, internal/atomicfile.Write), not an in-place truncate+rewrite")
	}
}

// TestRunDisposition_ConcurrentModificationRefusesInsteadOfLosingUpdate is
// ADJ-54's j-7 fix proof: a concurrent modification landing between
// runDisposition's initial read and its final write must refuse (exit 2,
// naming the concurrent modification) rather than silently clobber it —
// the exact lost-update scenario judged-j-7 named (two invocations
// targeting DIFFERENT findings of the same report, the second silently
// re-materializing the first's pre-race state while claiming success).
//
// Simulated via dispositionTestInterleave (ADJ-54's own sanctioned
// exception to this file's usual built-binary-only discipline for exactly
// this scenario: "simulate the interleaving... via a test seam or by
// driving the internals" — a real two-PROCESS race would need flaky
// OS-level timing to hit reliably; driving runDisposition directly,
// in-process, makes the race deterministic).
func TestRunDisposition_ConcurrentModificationRefusesInsteadOfLosingUpdate(t *testing.T) {
	findings := []artifact.Finding{
		{ID: "finding-a", Kind: artifact.FindingComputed, Text: "a's own claim"},
		{ID: "finding-b", Kind: artifact.FindingJudged, Text: "b's own claim"},
	}
	root := writeDispositionStoreRoot(t, "demo", buildDispositionFixture(t, findings, nil))
	path := reportPathFor(root, "demo")

	t.Cleanup(func() { dispositionTestInterleave = nil })
	dispositionTestInterleave = func(reportPath string) {
		// Clear the hook FIRST so the inner (concurrent) call below does
		// not recursively retrigger it — the hook must fire exactly once,
		// for the outer call only.
		dispositionTestInterleave = nil
		// The "concurrent" second invocation, landing first — on a
		// DIFFERENT finding than the outer call below, exactly j-7's
		// named scenario.
		if rc := runDisposition(root, "spec/demo", "finding-b", artifact.FindingFixed, "b's concurrent disposition", false, io.Discard, io.Discard); rc != 0 {
			t.Fatalf("test setup: concurrent finding-b disposition failed with rc=%d", rc)
		}
	}

	var stdout, stderr bytes.Buffer
	rc := runDisposition(root, "spec/demo", "finding-a", artifact.FindingAcceptedDeviation, "a's disposition", false, &stdout, &stderr)
	if rc != 2 {
		t.Fatalf("runDisposition (racing finding-a) = %d, want 2 (operational — concurrent modification detected); stdout=%s stderr=%s", rc, stdout.String(), stderr.String())
	}
	if !strings.Contains(stderr.String(), "concurrent") {
		t.Fatalf("stderr = %q, want it to name the concurrent modification", stderr.String())
	}

	// finding-b's concurrent disposition (the "winner", landed first) must
	// survive; finding-a's losing, refused write must not have clobbered
	// it, and finding-a itself must remain undispositioned (the refused
	// write never landed).
	after := decodeReportFile(t, path)
	fb, ok := findingByID(after.Findings, "finding-b")
	if !ok || fb.Disposition != artifact.FindingFixed || fb.Note != "b's concurrent disposition" {
		t.Fatalf("finding-b = %+v, want the concurrent disposition to have survived untouched", fb)
	}
	fa, ok := findingByID(after.Findings, "finding-a")
	if !ok || fa.Dispositioned() {
		t.Fatalf("finding-a = %+v, want it to remain undispositioned (the losing write was refused, never landed)", fa)
	}
}

// dispositionFixtureCovers is buildDispositionFixtureWithNotResurfaced's own
// hardcoded covers value — the "covering head" spec/finding-identity ac-1/
// ac-2 name as where a confirmed reaffirmation's carried-from: points.
const dispositionFixtureCovers = "1111111111111111111111111111111111111111"

// TestRunDisposition_ConfirmsCandidate_Reaffirmation_StampsCarriedFrom is
// spec/finding-identity ac-1/ac-2's "confirm as working-tree edit" proof:
// a live candidate (an undispositioned judged finding whose id matches a
// not-resurfaced: backing record) dispositioned with the SAME decision as
// the old ruling is a REAFFIRMATION — the disposition verb stamps
// carried-from: <covers-sha> and removes the now-resolved not-resurfaced
// entry.
func TestRunDisposition_ConfirmsCandidate_Reaffirmation_StampsCarriedFrom(t *testing.T) {
	findings := []artifact.Finding{
		{ID: "judged-a", Kind: artifact.FindingJudged, Text: "reworded new text"},
	}
	notResurfaced := []artifact.Finding{
		{ID: "judged-a", Kind: artifact.FindingJudged, Text: "old text", Disposition: artifact.FindingAcceptedDeviation, Note: "owner-ratified"},
	}
	root := writeDispositionStoreRoot(t, "demo", buildDispositionFixtureWithNotResurfaced(t, findings, notResurfaced, nil))
	path := reportPathFor(root, "demo")

	var stdout, stderr bytes.Buffer
	rc := runDisposition(root, "spec/demo", "judged-a", artifact.FindingAcceptedDeviation, "reaffirmed: still an intentional deviation", false, &stdout, &stderr)
	if rc != 0 {
		t.Fatalf("runDisposition = %d, want 0; stderr=%s", rc, stderr.String())
	}

	after := decodeReportFile(t, path)
	f, ok := findingByID(after.Findings, "judged-a")
	if !ok {
		t.Fatal("judged-a missing from findings after confirmation")
	}
	if f.Disposition != artifact.FindingAcceptedDeviation {
		t.Fatalf("Disposition = %q, want accepted-deviation", f.Disposition)
	}
	if f.CarriedFrom != dispositionFixtureCovers {
		t.Fatalf("CarriedFrom = %q, want the report's own covers %q (a reaffirmation — same ruling as the old ruling)", f.CarriedFrom, dispositionFixtureCovers)
	}
	if len(after.NotResurfaced) != 0 {
		t.Fatalf("NotResurfaced = %+v, want empty — a confirmed candidate's backing record must be removed", after.NotResurfaced)
	}

	// The frontmatter round-trips through the strict decode seam with
	// carried-from present (already proven at the schema level,
	// deviation_test.go — this is the disposition verb's own production of
	// that shape, driven end to end).
	if err := after.Validate(); err != nil {
		t.Fatalf("Validate(): %v", err)
	}
}

// TestRunDisposition_ConfirmsCandidate_Escalation_NoCarriedFrom is ac-2's
// escalation half: a live candidate dispositioned with a DIFFERENT decision
// than the old ruling is NOT a reaffirmation — no carried-from is stamped —
// but the old ruling's not-resurfaced backing record is still removed
// (superseded by the fresh, human-made decision).
func TestRunDisposition_ConfirmsCandidate_Escalation_NoCarriedFrom(t *testing.T) {
	findings := []artifact.Finding{
		{ID: "judged-a", Kind: artifact.FindingJudged, Text: "this is a real regression (confidence 0.93)"},
	}
	notResurfaced := []artifact.Finding{
		{ID: "judged-a", Kind: artifact.FindingJudged, Text: "looks cosmetic (confidence 0.35)", Disposition: artifact.FindingAcceptedDeviation, Note: "low confidence, deferred"},
	}
	root := writeDispositionStoreRoot(t, "demo", buildDispositionFixtureWithNotResurfaced(t, findings, notResurfaced, nil))
	path := reportPathFor(root, "demo")

	var stdout, stderr bytes.Buffer
	rc := runDisposition(root, "spec/demo", "judged-a", artifact.FindingFixed, "real regression, fixed in this PR", false, &stdout, &stderr)
	if rc != 0 {
		t.Fatalf("runDisposition = %d, want 0; stderr=%s", rc, stderr.String())
	}

	after := decodeReportFile(t, path)
	f, ok := findingByID(after.Findings, "judged-a")
	if !ok {
		t.Fatal("judged-a missing from findings after confirmation")
	}
	if f.Disposition != artifact.FindingFixed {
		t.Fatalf("Disposition = %q, want fixed (the human's own fresh decision)", f.Disposition)
	}
	if f.CarriedFrom != "" {
		t.Fatalf("CarriedFrom = %q, want empty — an escalation (different decision than the old ruling) must never be stamped as a reaffirmation", f.CarriedFrom)
	}
	if len(after.NotResurfaced) != 0 {
		t.Fatalf("NotResurfaced = %+v, want empty — the old ruling is superseded, its backing record removed either way", after.NotResurfaced)
	}
}

// TestRunDisposition_Amend_RecomputesCarriedFrom is spec/finding-identity
// judged-amend-stale-carried-from's fix proof: the --amend path applies the
// same carried-from discipline as first-writing. By the time an amend runs the
// backing record was already removed at the original confirmation, so the
// judged reaffirmation branch finds nothing and cannot correct an inherited
// stamp — the amend path must do it itself. carried-from is ac-2's
// confirmed-reaffirmation provenance ONLY; an amend that CHANGES the decision
// is not a reaffirmation of the ruling the stamp attested, so the inherited
// stamp must be CLEARED, while a note-only amend (decision unchanged) keeps it.
//
// Red-first (before the fix): the amend path replaced only Disposition and Note
// and never touched CarriedFrom, so amending a confirmed reaffirmation
// (accepted-deviation carrying carried-from) to fixed left carried-from
// standing on a decision that reaffirms nothing — misattributed provenance that
// passed validation silently into the frozen archive.
func TestRunDisposition_Amend_RecomputesCarriedFrom(t *testing.T) {
	// A live finding already confirmed as a reaffirmation: accepted-deviation
	// carrying carried-from: <covers-sha> — the exact shape runDisposition's own
	// reaffirmation branch produces, its backing record long since removed.
	stampedReaffirmation := func() []artifact.Finding {
		return []artifact.Finding{
			{ID: "judged-a", Kind: artifact.FindingJudged, Text: "a standing deviation", Disposition: artifact.FindingAcceptedDeviation, Note: "owner-ratified: reaffirmed", CarriedFrom: dispositionFixtureCovers},
		}
	}

	t.Run("amend to fixed clears the inherited stamp", func(t *testing.T) {
		root := writeDispositionStoreRoot(t, "demo", buildDispositionFixture(t, stampedReaffirmation(), nil))
		path := reportPathFor(root, "demo")

		var stdout, stderr bytes.Buffer
		rc := runDisposition(root, "spec/demo", "judged-a", artifact.FindingFixed, "actually resolved this pass", true /* amend */, &stdout, &stderr)
		if rc != 0 {
			t.Fatalf("runDisposition (amend to fixed) = %d, want 0; stderr=%s", rc, stderr.String())
		}

		after := decodeReportFile(t, path)
		f, ok := findingByID(after.Findings, "judged-a")
		if !ok || f.Disposition != artifact.FindingFixed || f.Note != "actually resolved this pass" {
			t.Fatalf("judged-a after amend = %+v, want fixed with the new rationale", f)
		}
		if f.CarriedFrom != "" {
			t.Fatalf("CarriedFrom = %q, want CLEARED — an amend to a DIFFERING decision reaffirms nothing (ac-2)", f.CarriedFrom)
		}
		if err := after.Validate(); err != nil {
			t.Fatalf("Validate() after amend: %v", err)
		}
	})

	t.Run("note-only amend (decision unchanged) keeps the stamp", func(t *testing.T) {
		root := writeDispositionStoreRoot(t, "demo", buildDispositionFixture(t, stampedReaffirmation(), nil))
		path := reportPathFor(root, "demo")

		var stdout, stderr bytes.Buffer
		rc := runDisposition(root, "spec/demo", "judged-a", artifact.FindingAcceptedDeviation, "owner-ratified: reworded, still a deviation", true /* amend */, &stdout, &stderr)
		if rc != 0 {
			t.Fatalf("runDisposition (note-only amend) = %d, want 0; stderr=%s", rc, stderr.String())
		}

		after := decodeReportFile(t, path)
		f, ok := findingByID(after.Findings, "judged-a")
		if !ok || f.Disposition != artifact.FindingAcceptedDeviation || f.Note != "owner-ratified: reworded, still a deviation" {
			t.Fatalf("judged-a after amend = %+v, want accepted-deviation with the new note", f)
		}
		if f.CarriedFrom != dispositionFixtureCovers {
			t.Fatalf("CarriedFrom = %q, want KEPT (%q) — the reaffirmation the stamp attests still holds when the decision is unchanged", f.CarriedFrom, dispositionFixtureCovers)
		}
	})
}

// TestRunDisposition_OrdinaryFinding_NoNotResurfacedEntry_Unaffected proves
// this story's addition is a no-op for the ordinary case: a finding with NO
// matching not-resurfaced: entry dispositions exactly as before — no
// carried-from, NotResurfaced (already empty) untouched.
func TestRunDisposition_OrdinaryFinding_NoNotResurfacedEntry_Unaffected(t *testing.T) {
	findings := []artifact.Finding{
		{ID: "computed-a", Kind: artifact.FindingComputed, Text: "declared boundary holds"},
	}
	root := writeDispositionStoreRoot(t, "demo", buildDispositionFixture(t, findings, nil))
	path := reportPathFor(root, "demo")

	var stdout, stderr bytes.Buffer
	rc := runDisposition(root, "spec/demo", "computed-a", artifact.FindingFixed, "reviewed", false, &stdout, &stderr)
	if rc != 0 {
		t.Fatalf("runDisposition = %d, want 0; stderr=%s", rc, stderr.String())
	}

	after := decodeReportFile(t, path)
	f, _ := findingByID(after.Findings, "computed-a")
	if f.CarriedFrom != "" {
		t.Fatalf("CarriedFrom = %q, want empty (no not-resurfaced counterpart existed)", f.CarriedFrom)
	}
	if len(after.NotResurfaced) != 0 {
		t.Fatalf("NotResurfaced = %+v, want still empty", after.NotResurfaced)
	}
}

// TestRunDisposition_CollisionBacking_ExitRampResolvesBacking is
// spec/finding-identity judged-collision-backing-regeneration-drain's
// disposition-verb state-table entry: with a backing record present,
// ReconcileJudged suffixes EVERY collision member, so the backing record alone
// owns the bare slug and its exit ramp (dispositionNotResurfaced) is reachable
// DURING the live collision — the human marks the bare slug fixed straight
// through, the suffixed live members untouched, and no "left in not-resurfaced /
// lineage ambiguous" disclosure is emitted (that branch and its
// IsCollisionBaseMemberID guard are dissolved).
func TestRunDisposition_CollisionBacking_ExitRampResolvesBacking(t *testing.T) {
	bin := buildVerdiBinary(t)

	// The shape ReconcileJudged now produces for a collision whose slug owns a
	// backing record: every live member suffixed, the backing record standing
	// alone under the bare slug in not-resurfaced.
	findings := []artifact.Finding{
		{ID: "judged-dup-collision-1", Kind: artifact.FindingJudged, Text: "first reading"},
		{ID: "judged-dup-collision-2", Kind: artifact.FindingJudged, Text: "second, different reading"},
		{ID: "judged-contract-violation-dup", Kind: artifact.FindingJudged, Text: "judge contract violation: 2 findings shared slug \"judged-dup\" within one run"},
	}
	notResurfaced := []artifact.Finding{
		{ID: "judged-dup", Kind: artifact.FindingJudged, Text: "an old ruling under the same slug", Disposition: artifact.FindingAcceptedDeviation, Note: "owner-ratified"},
	}
	root := writeDispositionStoreRoot(t, "demo", buildDispositionFixtureWithNotResurfaced(t, findings, notResurfaced, nil))
	path := reportPathFor(root, "demo")

	stdout, stderr, code := runDispositionBinary(t, bin, root, "spec/demo", "judged-dup", "fixed", "--rationale", "the underlying issue is genuinely resolved")
	if code != 0 {
		t.Fatalf("exit = %d, want 0 (resolve the backing record via its exit ramp during the live collision); stderr=%s", code, stderr)
	}

	// The exit ramp fired — released via the not-resurfaced path, never the old
	// "left in not-resurfaced / lineage ambiguous" collision disclosure.
	if !strings.Contains(stdout, "(not-resurfaced)") || !strings.Contains(stdout, "released") {
		t.Fatalf("stdout = %q, want the not-resurfaced exit-ramp release", stdout)
	}
	if strings.Contains(stdout, "left in not-resurfaced") || strings.Contains(stdout, "lineage ambiguous") {
		t.Fatalf("stdout = %q, want NO collision-backing-left disclosure (that branch is dissolved)", stdout)
	}

	after := decodeReportFile(t, path)

	// The backing record is released (fixed) — no longer in not-resurfaced.
	if _, ok := findingByID(after.NotResurfaced, "judged-dup"); ok {
		t.Fatalf("backing record judged-dup still present after `fixed` release: %+v", after.NotResurfaced)
	}
	// The suffixed live members are untouched and the report stays valid.
	for _, id := range []string{"judged-dup-collision-1", "judged-dup-collision-2"} {
		if m, ok := findingByID(after.Findings, id); !ok || m.Dispositioned() {
			t.Fatalf("live member %s = %+v (present=%v), want present and undispositioned", id, m, ok)
		}
	}
	if err := after.Validate(); err != nil {
		t.Fatalf("resulting report failed to validate: %v", err)
	}
}

// TestRunDisposition_ComputedFindingCollidingWithJudgedNotResurfaced_DoesNotDrain
// is spec/finding-identity judged-reaffirm-judged-kind-scope's fix proof: a
// computed finding and a judged not-resurfaced entry share the same
// boundary-derived id (computed `boundary-x` live+undispositioned; judged
// `boundary-x` a prior ruling a fresh judge run stopped reproducing). The
// reaffirmation/not-resurfaced machinery is judged-only, so dispositioning the
// COMPUTED finding must never drain the judged persisted record nor stamp
// carried-from onto the computed finding — even when the decisions coincide
// (accepted-deviation == accepted-deviation), the strongest form of the bug.
//
// Red-first (before the fix): the backing lookup resolved by bare id with no
// Kind check, so dispositioning the computed finding stamped carried-from onto
// it and silently removed the judged ruling's persisted record — an automatic
// drain of an ac-3 entry by an unrelated finding's disposition.
func TestRunDisposition_ComputedFindingCollidingWithJudgedNotResurfaced_DoesNotDrain(t *testing.T) {
	findings := []artifact.Finding{
		{ID: "boundary-x", Kind: artifact.FindingComputed, Text: "the declared boundary holds"},
	}
	notResurfaced := []artifact.Finding{
		{ID: "boundary-x", Kind: artifact.FindingJudged, Text: "an old judged ruling under the same slug", Disposition: artifact.FindingAcceptedDeviation, Note: "owner-ratified"},
	}
	root := writeDispositionStoreRoot(t, "demo", buildDispositionFixtureWithNotResurfaced(t, findings, notResurfaced, nil))
	path := reportPathFor(root, "demo")

	var stdout, stderr bytes.Buffer
	rc := runDisposition(root, "spec/demo", "boundary-x", artifact.FindingAcceptedDeviation, "computed boundary confirmed a deviation", false, &stdout, &stderr)
	if rc != 0 {
		t.Fatalf("runDisposition = %d, want 0; stderr=%s", rc, stderr.String())
	}

	after := decodeReportFile(t, path)
	// The COMPUTED finding is dispositioned in findings:, with NO carried-from —
	// carried-from is judged-reaffirmation provenance, never stamped on a
	// computed finding.
	cf, ok := findingByID(after.Findings, "boundary-x")
	if !ok || cf.Kind != artifact.FindingComputed || cf.Disposition != artifact.FindingAcceptedDeviation {
		t.Fatalf("computed boundary-x = %+v (present=%v), want dispositioned accepted-deviation", cf, ok)
	}
	if cf.CarriedFrom != "" {
		t.Fatalf("computed boundary-x CarriedFrom = %q, want empty — carried-from must never be stamped on a computed finding", cf.CarriedFrom)
	}
	// The JUDGED not-resurfaced entry is UNTOUCHED — never drained by the
	// unrelated computed finding's disposition (the ac-3 automatic-drain closed).
	nr, ok := findingByID(after.NotResurfaced, "boundary-x")
	if !ok {
		t.Fatalf("judged not-resurfaced boundary-x was drained by a computed finding's disposition: %+v", after.NotResurfaced)
	}
	if nr.Kind != artifact.FindingJudged || nr.Disposition != artifact.FindingAcceptedDeviation || nr.Note != "owner-ratified" {
		t.Fatalf("judged not-resurfaced boundary-x = %+v, want untouched (judged, accepted-deviation, owner-ratified)", nr)
	}
}

// budgetAcceptedDeviationCount computes the accepted-deviation budget the
// closure gate's spec-stale condition counts for a living report: SpecStale
// over the report's own findings: UNION its not-resurfaced: section, by unique
// content identity — identical to cmd/verdi/closuregate.go's
// checkSpecStaleCondition wiring. This is the exact budget
// spec/finding-identity ac-3 says a human marking a not-resurfaced entry
// `fixed` must RELEASE and marking it `accepted-deviation` must KEEP.
func budgetAcceptedDeviationCount(t *testing.T, path string) int {
	t.Helper()
	fm := decodeReportFile(t, path)
	return evidence.SpecStale(evidence.SpecStaleInput{
		Findings:         fm.Findings,
		OwnNotResurfaced: fm.NotResurfaced,
	}).AcceptedDeviationCount
}

// TestRunDisposition_NotResurfacedOnly_ExitRamp is spec/finding-identity
// judged-not-resurfaced-mark-fixed's fix proof: `verdi disposition` is the
// sanctioned human exit ramp for an id that lives SOLELY in not-resurfaced:
// (absent from findings:) — the primary ac-3 shape a fresh judge run never
// resurfaces. `fixed` removes the entry, releasing its identity from the
// spec-stale/feature-close budget (the human's explicit "marks it fixed",
// ac-3's letter finally whole — NOT the X-18 judge-drain, which was automatic
// uncounting on non-reproduction); `accepted-deviation` re-affirms it in place
// and it STAYS COUNTED. A genuinely absent id still exits 1.
//
// Red-first (before the fix): every not-resurfaced-only disposition exited 1
// "finding not found" — runDisposition's lookup searched only findings: and
// consulted not-resurfaced: only AFTER a live findings: entry was located.
func TestRunDisposition_NotResurfacedOnly_ExitRamp(t *testing.T) {
	bin := buildVerdiBinary(t)

	// A living report carrying TWO standing accepted deviations of distinct
	// content identity (align.Identity = Kind+ID+Text): one a live finding,
	// one archived in not-resurfaced:. The budget therefore starts at 2, so a
	// release proves it drops by EXACTLY one (to 1), never coincidentally to
	// zero.
	fixture := func(t *testing.T) (root, path string) {
		t.Helper()
		findings := []artifact.Finding{
			{ID: "judged-live", Kind: artifact.FindingJudged, Text: "a live standing deviation", Disposition: artifact.FindingAcceptedDeviation, Note: "owner-ratified: live"},
		}
		notResurfaced := []artifact.Finding{
			{ID: "judged-archived", Kind: artifact.FindingJudged, Text: "an archived standing deviation", Disposition: artifact.FindingAcceptedDeviation, Note: "owner-ratified: archived"},
		}
		root = writeDispositionStoreRoot(t, "demo", buildDispositionFixtureWithNotResurfaced(t, findings, notResurfaced, nil))
		return root, reportPathFor(root, "demo")
	}

	t.Run("fixed removes the entry and releases it from the budget", func(t *testing.T) {
		root, path := fixture(t)
		if got := budgetAcceptedDeviationCount(t, path); got != 2 {
			t.Fatalf("budget before = %d, want 2 (a live + an archived accepted deviation)", got)
		}

		stdout, stderr, code := runDispositionBinary(t, bin, root, "spec/demo", "judged-archived", "fixed", "--rationale", "confirmed fixed; retire the archived entry")
		if code != 0 {
			t.Fatalf("exit = %d, want 0 (the sanctioned not-resurfaced exit ramp); stderr=%s", code, stderr)
		}
		t.Logf("fixed stdout: %s", strings.TrimRight(stdout, "\n"))
		if !strings.Contains(stdout, "not-resurfaced") {
			t.Fatalf("stdout = %q, want it to name the not-resurfaced section the id was found in", stdout)
		}

		after := decodeReportFile(t, path)
		if _, ok := findingByID(after.NotResurfaced, "judged-archived"); ok {
			t.Fatalf("judged-archived still present in not-resurfaced after `fixed`: %+v", after.NotResurfaced)
		}
		if _, ok := findingByID(after.Findings, "judged-archived"); ok {
			t.Fatalf("judged-archived leaked INTO findings: on a not-resurfaced disposition: %+v", after.Findings)
		}
		// judged-not-resurfaced-reaffirm-provenance: a `fixed` release is NOT a
		// reaffirmation, so it stamps no carried-from anywhere — the surviving
		// live finding stays byte-clean.
		if live, ok := findingByID(after.Findings, "judged-live"); !ok || live.CarriedFrom != "" {
			t.Fatalf("judged-live = %+v (present=%v), want no carried-from — a release never stamps reaffirmation provenance", live, ok)
		}
		if got := budgetAcceptedDeviationCount(t, path); got != 1 {
			t.Fatalf("budget after `fixed` = %d, want 1 (dropped by exactly one — the archived identity released)", got)
		}
		// The surviving body still renders a well-formed (now empty)
		// not-resurfaced section, and the released entry's own bullet is gone.
		body := readFile(t, path)
		if bytes.Contains(body, []byte("an archived standing deviation")) {
			t.Fatalf("body still contains the released entry's text; body:\n%s", body)
		}
	})

	t.Run("accepted-deviation reaffirms in place and stays counted", func(t *testing.T) {
		root, path := fixture(t)
		if got := budgetAcceptedDeviationCount(t, path); got != 2 {
			t.Fatalf("budget before = %d, want 2", got)
		}

		stdout, stderr, code := runDispositionBinary(t, bin, root, "spec/demo", "judged-archived", "accepted-deviation", "--rationale", "re-affirmed: still a standing deviation")
		if code != 0 {
			t.Fatalf("exit = %d, want 0; stderr=%s", code, stderr)
		}
		t.Logf("accepted-deviation stdout: %s", strings.TrimRight(stdout, "\n"))
		if !strings.Contains(stdout, "not-resurfaced") {
			t.Fatalf("stdout = %q, want it to name the not-resurfaced section", stdout)
		}

		after := decodeReportFile(t, path)
		f, ok := findingByID(after.NotResurfaced, "judged-archived")
		if !ok {
			t.Fatalf("judged-archived must STAY in not-resurfaced after `accepted-deviation` (re-affirmed, never released): %+v", after.NotResurfaced)
		}
		if f.Disposition != artifact.FindingAcceptedDeviation || f.Note != "re-affirmed: still a standing deviation" {
			t.Fatalf("judged-archived = %+v, want accepted-deviation with the rationale updated in place", f)
		}
		// judged-not-resurfaced-reaffirm-provenance: an in-place reaffirmation is
		// a confirmed reaffirmation of the standing ruling at the current covering
		// head, so it carries carried-from: <covers-sha> exactly like the
		// candidate-path reaffirmation (ac-2) — making a re-confirmed entry
		// distinguishable from one that was never re-confirmed.
		if f.CarriedFrom != dispositionFixtureCovers {
			t.Fatalf("judged-archived CarriedFrom = %q, want the report's own covers %q (a confirmed in-place reaffirmation)", f.CarriedFrom, dispositionFixtureCovers)
		}
		if got := budgetAcceptedDeviationCount(t, path); got != 2 {
			t.Fatalf("budget after `accepted-deviation` = %d, want 2 (unchanged — a re-affirmation is never a release)", got)
		}
		// The updated rationale is reflected in the human-legible body too.
		if !bytes.Contains(readFile(t, path), []byte("re-affirmed: still a standing deviation")) {
			t.Fatalf("body does not carry the updated not-resurfaced rationale; body:\n%s", readFile(t, path))
		}
	})

	t.Run("fixed with sibling not-resurfaced entries removes only the target line", func(t *testing.T) {
		// Two archived accepted deviations: fixing one must drop ONLY its own
		// body line (removeWholeLine's branch — distinct from the sole-entry
		// "(none)" substitution above) and leave the sibling entirely intact.
		notResurfaced := []artifact.Finding{
			{ID: "judged-arch-1", Kind: artifact.FindingJudged, Text: "first archived deviation", Disposition: artifact.FindingAcceptedDeviation, Note: "owner-ratified: one"},
			{ID: "judged-arch-2", Kind: artifact.FindingJudged, Text: "second archived deviation", Disposition: artifact.FindingAcceptedDeviation, Note: "owner-ratified: two"},
		}
		root := writeDispositionStoreRoot(t, "demo", buildDispositionFixtureWithNotResurfaced(t, nil, notResurfaced, nil))
		path := reportPathFor(root, "demo")
		if got := budgetAcceptedDeviationCount(t, path); got != 2 {
			t.Fatalf("budget before = %d, want 2 (two archived accepted deviations)", got)
		}

		_, stderr, code := runDispositionBinary(t, bin, root, "spec/demo", "judged-arch-1", "fixed", "--rationale", "confirmed fixed")
		if code != 0 {
			t.Fatalf("exit = %d, want 0; stderr=%s", code, stderr)
		}

		after := decodeReportFile(t, path)
		if _, ok := findingByID(after.NotResurfaced, "judged-arch-1"); ok {
			t.Fatalf("judged-arch-1 still present after `fixed`: %+v", after.NotResurfaced)
		}
		sib, ok := findingByID(after.NotResurfaced, "judged-arch-2")
		if !ok {
			t.Fatalf("sibling judged-arch-2 must survive the removal untouched: %+v", after.NotResurfaced)
		}
		if sib.Disposition != artifact.FindingAcceptedDeviation || sib.Note != "owner-ratified: two" {
			t.Fatalf("sibling judged-arch-2 = %+v, want untouched accepted-deviation", sib)
		}
		if got := budgetAcceptedDeviationCount(t, path); got != 1 {
			t.Fatalf("budget after = %d, want 1 (only the target released)", got)
		}
		body := readFile(t, path)
		if bytes.Contains(body, []byte("first archived deviation")) {
			t.Fatalf("body still contains the removed entry's text; body:\n%s", body)
		}
		if !bytes.Contains(body, []byte("second archived deviation")) {
			t.Fatalf("body dropped the sibling's line during a single-entry removal; body:\n%s", body)
		}
	})

	t.Run("a genuinely absent id still exits 1", func(t *testing.T) {
		root, path := fixture(t)
		before := readFile(t, path)

		_, stderr, code := runDispositionBinary(t, bin, root, "spec/demo", "no-such-finding", "fixed", "--rationale", "x")
		if code != 1 {
			t.Fatalf("exit = %d, want 1 (verdict — genuinely absent from both findings: and not-resurfaced:); stderr=%s", code, stderr)
		}
		if !strings.Contains(stderr, "no-such-finding") || !strings.Contains(stderr, "not found") {
			t.Fatalf("stderr = %q, want it to name the absent id as not found", stderr)
		}
		assertUnchanged(t, path, before)
	})
}
