package main

import (
	"bytes"
	"context"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/jyang234/verdi/internal/align"
	"github.com/jyang234/verdi/internal/artifact"
	"github.com/jyang234/verdi/internal/storyresolve"
)

// buildDispositionFixture renders a minimal, schema-valid deviation-report.md
// via the REAL renderer (align.RenderBody/RenderMarkdown — never a hand-typed
// markdown string), so every fixture this file builds is guaranteed
// byte-consistent with what `verdi align` itself would have produced, and
// self-validates before handing it back (never build a fixture that isn't
// itself a legal report).
func buildDispositionFixture(t *testing.T, findings []artifact.Finding, frozen *artifact.Frozen) []byte {
	t.Helper()
	fm := &artifact.DeviationFrontmatter{
		Schema:   "verdi.deviation/v1",
		Covers:   "1111111111111111111111111111111111111111",
		Findings: findings,
		Digest:   "sha256:" + strings.Repeat("0", 64),
		Frozen:   frozen,
	}
	if err := fm.Validate(); err != nil {
		t.Fatalf("test setup: fixture frontmatter invalid: %v", err)
	}
	body := align.RenderBody(findings, nil, nil, nil)
	return align.RenderMarkdown(fm, body)
}

// writeDispositionStoreRoot builds a plain, non-git store root — `verdi
// disposition` never touches git or the judge (spec/disposition-verb dc-5:
// "a pure, local, offline read-mutate-write") — containing verdi.yaml and a
// single deviation-report.md at
// .verdi/specs/active/<specName>/deviation-report.md.
func writeDispositionStoreRoot(t *testing.T, specName string, reportMD []byte) string {
	t.Helper()
	root := t.TempDir()
	writeTestFile(t, filepath.Join(root, ".verdi", "verdi.yaml"), []byte("schema: verdi.layout/v1\n"))
	writeTestFile(t, reportPathFor(root, specName), reportMD)
	return root
}

func writeTestFile(t *testing.T, path string, content []byte) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir for %s: %v", path, err)
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func reportPathFor(root, specName string) string {
	return filepath.Join(root, ".verdi", "specs", "active", specName, "deviation-report.md")
}

func readFile(t *testing.T, path string) []byte {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}
	return data
}

func assertUnchanged(t *testing.T, path string, before []byte) {
	t.Helper()
	after := readFile(t, path)
	if !bytes.Equal(before, after) {
		t.Fatalf("%s was written to despite a refusal (no partial write allowed):\n--- before ---\n%s\n--- after ---\n%s", path, before, after)
	}
}

// runDispositionBinary execs the built verdi binary's "disposition" verb
// with args, cwd=dir, capturing stdout/stderr separately — driving the real
// binary, never cmdDisposition/runDisposition in-process (obligation
// disposition-verb--ac-1--behavioral / --ac-2--behavioral).
func runDispositionBinary(t *testing.T, bin, dir string, args ...string) (stdout, stderr string, code int) {
	t.Helper()
	cmd := exec.Command(bin, append([]string{"disposition"}, args...)...)
	cmd.Dir = dir
	var outBuf, errBuf bytes.Buffer
	cmd.Stdout = &outBuf
	cmd.Stderr = &errBuf
	err := cmd.Run()
	if err != nil {
		if ee, ok := err.(*exec.ExitError); ok {
			return outBuf.String(), errBuf.String(), ee.ExitCode()
		}
		t.Fatalf("running verdi disposition %v: %v", args, err)
	}
	return outBuf.String(), errBuf.String(), 0
}

// TestRunDisposition_RecordsInPlace_DigestAndIntegrityPreserved is
// obligation/disposition-verb--ac-1--behavioral: drives the built binary
// against a LIVING report generated by a real (non-freeze) `verdi align` run
// (buildAlignRepo + alignFakeJudgeOK, mirroring cmd/verdi/align_test.go's own
// harness — a genuine judge exchange, not a hand-typed fixture), then
// dispositions first the computed finding as `fixed` and then the judged
// finding as `accepted-deviation` (both decision values, sequentially, on the
// SAME report), proving each write: updates the target finding's frontmatter
// AND its rendered body bullet, leaves every OTHER finding byte-identical,
// and leaves digest/integrity byte-identical AND independently
// reverifiable — align.ComputeDigest recomputed from a fresh align.Compute
// over the same fixture tree still equals the stored digest, and
// align.VerifyIntegrity still succeeds against the genuine judge exchange.
func TestRunDisposition_RecordsInPlace_DigestAndIntegrityPreserved(t *testing.T) {
	bin := buildVerdiBinary(t)
	repo := buildAlignRepo(t)
	svcDir := filepath.Join(repo.Dir, "loansvc")
	reportPath := filepath.Join(repo.Dir, ".verdi", "specs", "active", "stale-decline", "deviation-report.md")

	deps := alignDeps{Runner: alignRunner(svcDir), JudgeCmd: alignFakeJudgeOK(t)}
	var out, errb bytes.Buffer
	if got := runAlign(context.Background(), repo.Dir, false, deps, &out, &errb); got != 0 {
		t.Fatalf("runAlign (setup) = %d, want 0; stderr=%s", got, errb.String())
	}

	spec, err := storyresolve.ResolveBuildSpec(repo.Dir, "feature/stale-decline")
	if err != nil {
		t.Fatalf("test setup: ResolveBuildSpec: %v", err)
	}

	verifyDigestAndIntegrity := func(t *testing.T, fm *artifact.DeviationFrontmatter) {
		t.Helper()
		computed, err := align.Compute(context.Background(), align.ComputedInput{Root: repo.Dir, Runner: alignRunner(svcDir), Spec: spec, Covers: fm.Covers})
		if err != nil {
			t.Fatalf("independent align.Compute: %v", err)
		}
		if err := align.VerifyDigest(fm, computed); err != nil {
			t.Fatalf("align.VerifyDigest: %v", err)
		}
		if err := align.VerifyIntegrity(fm); err != nil {
			t.Fatalf("align.VerifyIntegrity: %v", err)
		}
	}

	before := decodeReportFile(t, reportPath)
	verifyDigestAndIntegrity(t, before)

	judgedBefore, ok := findingByID(before.Findings, "judged-j-1")
	if !ok || judgedBefore.Dispositioned() {
		t.Fatalf("test setup: want an undispositioned judged finding j-1, got %+v (present=%v)", judgedBefore, ok)
	}
	var computedBefore artifact.Finding
	for _, f := range before.Findings {
		if f.Kind == artifact.FindingComputed {
			computedBefore = f
		}
	}
	if computedBefore.ID == "" || computedBefore.Dispositioned() {
		t.Fatalf("test setup: want an undispositioned computed finding, got %+v", computedBefore)
	}

	// Step 1: disposition the COMPUTED finding as `fixed`.
	_, stderr, code := runDispositionBinary(t, bin, repo.Dir, "spec/stale-decline", computedBefore.ID, "fixed", "--rationale", "regenerated boundary contract confirms the declared edge")
	if code != 0 {
		t.Fatalf("verdi disposition (computed, fixed) exit = %d, want 0; stderr=%s", code, stderr)
	}

	afterStep1 := decodeReportFile(t, reportPath)
	cf, ok := findingByID(afterStep1.Findings, computedBefore.ID)
	if !ok || cf.Disposition != artifact.FindingFixed || cf.Note != "regenerated boundary contract confirms the declared edge" {
		t.Fatalf("computed finding after step 1 = %+v, want disposition fixed with the given rationale", cf)
	}
	jf, ok := findingByID(afterStep1.Findings, "judged-j-1")
	if !ok || jf != judgedBefore {
		t.Fatalf("judged finding j-1 changed during step 1's unrelated write: before=%+v after=%+v", judgedBefore, jf)
	}
	if afterStep1.Digest != before.Digest || afterStep1.Integrity != before.Integrity {
		t.Fatalf("digest/integrity changed after step 1: before={digest:%s integrity:%s} after={digest:%s integrity:%s}",
			before.Digest, before.Integrity, afterStep1.Digest, afterStep1.Integrity)
	}
	verifyDigestAndIntegrity(t, afterStep1)

	step1Bytes := readFile(t, reportPath)
	if !bytes.Contains(step1Bytes, []byte(align.RenderFindingLine(cf))) {
		t.Fatalf("body does not contain the updated computed-finding bullet line; body:\n%s", step1Bytes)
	}

	// Step 2: disposition the JUDGED finding (j-1) as `accepted-deviation`.
	_, stderr2, code2 := runDispositionBinary(t, bin, repo.Dir, "spec/stale-decline", "judged-j-1", "accepted-deviation", "--rationale", "owner-ratified: intentional, tracked separately")
	if code2 != 0 {
		t.Fatalf("verdi disposition (judged, accepted-deviation) exit = %d, want 0; stderr=%s", code2, stderr2)
	}

	afterStep2 := decodeReportFile(t, reportPath)
	jf2, ok := findingByID(afterStep2.Findings, "judged-j-1")
	if !ok || jf2.Disposition != artifact.FindingAcceptedDeviation || jf2.Note != "owner-ratified: intentional, tracked separately" {
		t.Fatalf("judged finding after step 2 = %+v, want disposition accepted-deviation with the given rationale", jf2)
	}
	// The computed finding's step-1 write must survive step 2 untouched.
	cf2, ok := findingByID(afterStep2.Findings, computedBefore.ID)
	if !ok || cf2 != cf {
		t.Fatalf("computed finding changed during step 2's unrelated write: before=%+v after=%+v", cf, cf2)
	}
	if afterStep2.Digest != before.Digest || afterStep2.Integrity != before.Integrity {
		t.Fatalf("digest/integrity changed after step 2: before={digest:%s integrity:%s} after={digest:%s integrity:%s}",
			before.Digest, before.Integrity, afterStep2.Digest, afterStep2.Integrity)
	}
	verifyDigestAndIntegrity(t, afterStep2)

	step2Bytes := readFile(t, reportPath)
	if !bytes.Contains(step2Bytes, []byte(align.RenderFindingLine(jf2))) {
		t.Fatalf("body does not contain the updated judged-finding bullet line; body:\n%s", step2Bytes)
	}
	if bytes.Contains(step2Bytes, []byte(align.RenderFindingLine(judgedBefore))) {
		t.Fatalf("body still contains j-1's OLD (undispositioned) bullet line; body:\n%s", step2Bytes)
	}
}

// TestRunDisposition_SurvivesFreeze is obligation/disposition-verb--ac-3--behavioral
// (mirroring cmd/verdi/align_test.go's TestRunAlign_FreezePreservesDispositions,
// the same drifting-judge harness the T.1/D6-24 keep-genuine fix proved
// against): generates a living report via a real (non-freeze) `verdi align`
// run, dispositions EVERY finding using the BUILT `verdi disposition` binary
// — never by direct struct/file mutation — then runs `verdi align --freeze`
// with a judge that would produce DIFFERENT content on a hypothetical
// regeneration (alignFakeJudgeDrift). Proves align.FreezeInPlace fires: the
// frozen report's findings, dispositions, and notes are byte-identical to
// what the disposition verb wrote, and the drifting judge's content is
// nowhere in the frozen output.
func TestRunDisposition_SurvivesFreeze(t *testing.T) {
	bin := buildVerdiBinary(t)
	repo := buildAlignRepo(t)
	svcDir := filepath.Join(repo.Dir, "loansvc")
	reportPath := filepath.Join(repo.Dir, ".verdi", "specs", "active", "stale-decline", "deviation-report.md")

	living := alignDeps{Runner: alignRunner(svcDir), JudgeCmd: alignFakeJudgeOK(t)}
	var out, errb bytes.Buffer
	if got := runAlign(context.Background(), repo.Dir, false, living, &out, &errb); got != 0 {
		t.Fatalf("runAlign (living) = %d, want 0; stderr=%s", got, errb.String())
	}

	before := decodeReportFile(t, reportPath)
	if len(before.Findings) == 0 {
		t.Fatal("test setup: living report carries no findings to disposition")
	}

	// Disposition EVERY finding via the built binary — never by direct
	// struct/file mutation (the obligation's own bar).
	for _, f := range before.Findings {
		decision := artifact.FindingFixed
		rationale := "fixed by the build"
		if f.Kind == artifact.FindingJudged {
			decision = artifact.FindingAcceptedDeviation
			rationale = "owner-ratified: intentional, tracked separately"
		}
		_, stderr, code := runDispositionBinary(t, bin, repo.Dir, "spec/stale-decline", f.ID, string(decision), "--rationale", rationale)
		if code != 0 {
			t.Fatalf("verdi disposition %s: exit = %d, want 0; stderr=%s", f.ID, code, stderr)
		}
	}

	afterDispositioning := decodeReportFile(t, reportPath)
	if !artifact.AllDispositioned(afterDispositioning.Findings) {
		t.Fatalf("not every finding is dispositioned after driving the verb over all of them: %+v", afterDispositioning.Findings)
	}
	dispositioned := make(map[string]artifact.Finding, len(afterDispositioning.Findings))
	for _, f := range afterDispositioning.Findings {
		dispositioned[f.ID] = f
	}

	// Freeze — with a judge that now DRIFTS (different id + text). A
	// faithful freeze must ignore it and stamp the disposition-verb-adjudicated
	// living report as-is (align.FreezeInPlace, PR #99 + the D6-24/T.1
	// keep-genuine guard, PR #101).
	frozenDeps := alignDeps{Runner: alignRunner(svcDir), JudgeCmd: alignFakeJudgeDrift(t)}
	var out2, errb2 bytes.Buffer
	if got := runAlign(context.Background(), repo.Dir, true, frozenDeps, &out2, &errb2); got != 0 {
		t.Fatalf("runAlign (freeze) = %d, want 0; stderr=%s", got, errb2.String())
	}

	frozen := decodeReportFile(t, reportPath)
	if frozen.Frozen == nil {
		t.Fatal("frozen report carries no Frozen stamp")
	}
	if len(frozen.Findings) != len(dispositioned) {
		t.Fatalf("frozen report has %d findings, want %d (the disposition-verb-written set)", len(frozen.Findings), len(dispositioned))
	}
	for _, f := range frozen.Findings {
		want, ok := dispositioned[f.ID]
		if !ok {
			t.Fatalf("frozen finding %s was not among the disposition-verb-written set: %+v", f.ID, f)
		}
		if f != want {
			t.Fatalf("frozen finding %s = %+v, want the disposition-verb-written %+v (freeze must be verbatim)", f.ID, f, want)
		}
	}

	// The drifting judge's content must be nowhere in the frozen output —
	// proof that the D6-24 keep-genuine/freeze-in-place path fired rather
	// than a hypothetical re-judge leaking through.
	frozenBytes := readFile(t, reportPath)
	for _, driftSubstr := range []string{"j-drift", "a fresh, differently-worded semantic reading"} {
		if bytes.Contains(frozenBytes, []byte(driftSubstr)) {
			t.Fatalf("frozen report contains the drifting judge's content (%q) — freeze re-judged instead of preserving the disposition-verb-written report:\n%s", driftSubstr, frozenBytes)
		}
	}
}

// TestRunDisposition_JudgeNewlineTextRendersSingleLineAndDispositionsCleanly
// is ADJ-53's j-4 fix proof, end to end: a real (non-freeze) `verdi align`
// run against a judge whose finding text carries an embedded newline
// (alignFakeJudgeNewlineText, the same fixture shape as
// TestRunJudgeOnce_NewlineInTextIsNormalized's unit-level proof) must
// produce a report whose body renders that finding as exactly ONE line,
// and the finding must then disposition cleanly through the BUILT binary —
// the exact permanent-brick scenario judged-j-4 named, now closed at the
// source (internal/align/judge.go's normalizeJudgeText) rather than taught
// to the verb (ADJ-53's own chosen option).
func TestRunDisposition_JudgeNewlineTextRendersSingleLineAndDispositionsCleanly(t *testing.T) {
	bin := buildVerdiBinary(t)
	repo := buildAlignRepo(t)
	svcDir := filepath.Join(repo.Dir, "loansvc")
	reportPath := filepath.Join(repo.Dir, ".verdi", "specs", "active", "stale-decline", "deviation-report.md")

	deps := alignDeps{Runner: alignRunner(svcDir), JudgeCmd: alignFakeJudgeNewlineText(t)}
	var out, errb bytes.Buffer
	if got := runAlign(context.Background(), repo.Dir, false, deps, &out, &errb); got != 0 {
		t.Fatalf("runAlign (newline-text judge) = %d, want 0; stderr=%s", got, errb.String())
	}

	before := decodeReportFile(t, reportPath)
	jf, ok := findingByID(before.Findings, "judged-j-newline")
	if !ok {
		t.Fatalf("test setup: no judged-j-newline finding among %+v", before.Findings)
	}
	if strings.ContainsAny(jf.Text, "\n\r") {
		t.Fatalf("finding text = %q, contains a raw newline/CR — normalizeJudgeText should have stripped it at the align/judge seam", jf.Text)
	}
	if !strings.Contains(jf.Text, "line one") || !strings.Contains(jf.Text, "line two") {
		t.Fatalf("finding text = %q, want it to still carry both halves of the judge's text", jf.Text)
	}

	// The report's BODY must render this finding as exactly ONE whole
	// line — not merely "somewhere as a substring" (strings.Split on "\n"
	// is the same line-boundary-anchored check the verb's own
	// replaceWholeLine uses, ADJ-52's j-2 fix).
	wantLine := align.RenderFindingLine(jf)
	bodyLines := strings.Split(string(readFile(t, reportPath)), "\n")
	matches := 0
	for _, l := range bodyLines {
		if l == wantLine {
			matches++
		}
	}
	if matches != 1 {
		t.Fatalf("expected exactly one whole-line match for the finding's rendered line, found %d; body:\n%s", matches, readFile(t, reportPath))
	}

	// Disposition it — must succeed cleanly. Before ADJ-53's source fix,
	// this exact scenario permanently bricked (judged-j-4): the verb's
	// whole-line matcher could never match a multi-line "line" against any
	// single split-line element.
	_, stderr, code := runDispositionBinary(t, bin, repo.Dir, "spec/stale-decline", "judged-j-newline", "accepted-deviation", "--rationale", "confirmed normalized to a single line; dispositions cleanly")
	if code != 0 {
		t.Fatalf("verdi disposition (newline-text finding) exit = %d, want 0 (must disposition cleanly); stderr=%s", code, stderr)
	}

	after := decodeReportFile(t, reportPath)
	f, ok := findingByID(after.Findings, "judged-j-newline")
	if !ok || f.Disposition != artifact.FindingAcceptedDeviation || f.Note != "confirmed normalized to a single line; dispositions cleanly" {
		t.Fatalf("judged-j-newline = %+v, want disposition accepted-deviation with the given rationale", f)
	}
}

// TestRunDisposition_Refusals is obligation/disposition-verb--ac-2--behavioral:
// table-driven, driving the built binary against fixture stores, proving
// every named refusal is a verdict (exit 1) or operational error (exit 2) as
// ac-2 specifies, and that every refusal writes NOTHING (byte-identical
// report before/after) — while the one deliberate write path (--amend
// against an existing disposition) actually replaces it.
func TestRunDisposition_Refusals(t *testing.T) {
	bin := buildVerdiBinary(t)

	livingFindings := func() []artifact.Finding {
		return []artifact.Finding{
			{ID: "computed-a", Kind: artifact.FindingComputed, Text: "declared boundary holds"},
			{ID: "judged-b", Kind: artifact.FindingJudged, Text: "a judged reading", Disposition: artifact.FindingFixed, Note: "already handled"},
		}
	}

	t.Run("unknown finding id refuses and names it", func(t *testing.T) {
		root := writeDispositionStoreRoot(t, "demo", buildDispositionFixture(t, livingFindings(), nil))
		path := reportPathFor(root, "demo")
		before := readFile(t, path)

		_, stderr, code := runDispositionBinary(t, bin, root, "spec/demo", "no-such-finding", "fixed", "--rationale", "x")
		if code != 1 {
			t.Fatalf("exit = %d, want 1 (verdict); stderr=%s", code, stderr)
		}
		if !strings.Contains(stderr, "no-such-finding") {
			t.Fatalf("stderr = %q, want it to name the unknown finding id", stderr)
		}
		assertUnchanged(t, path, before)
	})

	t.Run("already dispositioned without --amend refuses and names it", func(t *testing.T) {
		root := writeDispositionStoreRoot(t, "demo", buildDispositionFixture(t, livingFindings(), nil))
		path := reportPathFor(root, "demo")
		before := readFile(t, path)

		_, stderr, code := runDispositionBinary(t, bin, root, "spec/demo", "judged-b", "accepted-deviation", "--rationale", "y")
		if code != 1 {
			t.Fatalf("exit = %d, want 1 (verdict); stderr=%s", code, stderr)
		}
		if !strings.Contains(stderr, "judged-b") {
			t.Fatalf("stderr = %q, want it to name the already-dispositioned finding", stderr)
		}
		assertUnchanged(t, path, before)
	})

	t.Run("amend replaces an existing disposition", func(t *testing.T) {
		root := writeDispositionStoreRoot(t, "demo", buildDispositionFixture(t, livingFindings(), nil))
		path := reportPathFor(root, "demo")

		_, stderr, code := runDispositionBinary(t, bin, root, "spec/demo", "judged-b", "accepted-deviation", "--rationale", "amended rationale", "--amend")
		if code != 0 {
			t.Fatalf("exit = %d, want 0; stderr=%s", code, stderr)
		}
		after := decodeReportFile(t, path)
		f, ok := findingByID(after.Findings, "judged-b")
		if !ok || f.Disposition != artifact.FindingAcceptedDeviation || f.Note != "amended rationale" {
			t.Fatalf("judged-b = %+v, want amended to accepted-deviation with the new rationale", f)
		}
		other, ok := findingByID(after.Findings, "computed-a")
		if !ok || other.Dispositioned() {
			t.Fatalf("computed-a changed during an unrelated amend: %+v", other)
		}
	})

	t.Run("amend with nothing to amend refuses and names it", func(t *testing.T) {
		root := writeDispositionStoreRoot(t, "demo", buildDispositionFixture(t, livingFindings(), nil))
		path := reportPathFor(root, "demo")
		before := readFile(t, path)

		_, stderr, code := runDispositionBinary(t, bin, root, "spec/demo", "computed-a", "fixed", "--rationale", "z", "--amend")
		if code != 1 {
			t.Fatalf("exit = %d, want 1 (verdict); stderr=%s", code, stderr)
		}
		if !strings.Contains(stderr, "computed-a") {
			t.Fatalf("stderr = %q, want it to name the finding with nothing to amend", stderr)
		}
		assertUnchanged(t, path, before)
	})

	t.Run("frozen report refuses unconditionally, including with --amend", func(t *testing.T) {
		frozen := &artifact.Frozen{At: "2024-01-01", Commit: "1111111111111111111111111111111111111111"}
		root := writeDispositionStoreRoot(t, "demo", buildDispositionFixture(t, livingFindings(), frozen))
		path := reportPathFor(root, "demo")
		before := readFile(t, path)

		_, stderr, code := runDispositionBinary(t, bin, root, "spec/demo", "computed-a", "fixed", "--rationale", "z")
		if code != 1 {
			t.Fatalf("exit = %d, want 1 (verdict); stderr=%s", code, stderr)
		}
		if !strings.Contains(stderr, "frozen") {
			t.Fatalf("stderr = %q, want it to name the report frozen", stderr)
		}
		assertUnchanged(t, path, before)

		_, stderr2, code2 := runDispositionBinary(t, bin, root, "spec/demo", "judged-b", "accepted-deviation", "--rationale", "z", "--amend")
		if code2 != 1 {
			t.Fatalf("--amend exit = %d, want 1 (verdict); stderr=%s", code2, stderr2)
		}
		if !strings.Contains(stderr2, "frozen") {
			t.Fatalf("--amend stderr = %q, want it to name the report frozen", stderr2)
		}
		assertUnchanged(t, path, before)
	})

	t.Run("body/frontmatter desync for a finding refuses as a verdict, never an internal error (ADJ-53 j-5)", func(t *testing.T) {
		findings := livingFindings()
		reportMD := buildDispositionFixture(t, findings, nil)

		// Corrupt the body: replace computed-a's genuine rendered line with
		// hand-drifted text bearing no relation to its frontmatter entry —
		// the exact "body hand-drifted from its frontmatter" scenario j-5
		// named. This is a condition of the REPORT'S OWN STATE (dc-3's
		// verdict class), never an operational failure; ADJ-53 reclassifies
		// it from exit 2 "internal error" to exit 1.
		oldLine := align.RenderFindingLine(findings[0])
		corrupted := bytes.Replace(reportMD, []byte(oldLine), []byte("- **computed-a** [UNDISPOSITIONED]: a hand-drifted line bearing no relation to the frontmatter"), 1)
		if bytes.Equal(corrupted, reportMD) {
			t.Fatal("test setup: expected computed-a's rendered line to be present and replaceable")
		}

		root := writeDispositionStoreRoot(t, "demo", corrupted)
		path := reportPathFor(root, "demo")
		before := readFile(t, path)

		_, stderr, code := runDispositionBinary(t, bin, root, "spec/demo", "computed-a", "fixed", "--rationale", "z")
		if code != 1 {
			t.Fatalf("exit = %d, want 1 (verdict — a body/frontmatter desync, ADJ-53's j-5 reclassification); stderr=%s", code, stderr)
		}
		if strings.Contains(stderr, "internal error") {
			t.Fatalf("stderr = %q, must NOT say 'internal error' — this misattributes an externally-authored report condition to a tool bug (ADJ-53)", stderr)
		}
		if !strings.Contains(stderr, "computed-a") || !strings.Contains(stderr, "drifted") {
			t.Fatalf("stderr = %q, want it to honestly name the finding and the drift", stderr)
		}
		assertUnchanged(t, path, before)
	})

	t.Run("missing deviation-report.md is an operational error", func(t *testing.T) {
		root := t.TempDir()
		writeTestFile(t, filepath.Join(root, ".verdi", "verdi.yaml"), []byte("schema: verdi.layout/v1\n"))

		_, stderr, code := runDispositionBinary(t, bin, root, "spec/nope", "computed-a", "fixed", "--rationale", "z")
		if code != 2 {
			t.Fatalf("exit = %d, want 2 (operational); stderr=%s", code, stderr)
		}
	})

	t.Run("malformed report fails strict decode as an operational error", func(t *testing.T) {
		root := writeDispositionStoreRoot(t, "demo", []byte("---\nschema: verdi.deviation/v1\nunknown_field: true\n---\nbody\n"))

		_, stderr, code := runDispositionBinary(t, bin, root, "spec/demo", "computed-a", "fixed", "--rationale", "z")
		if code != 2 {
			t.Fatalf("exit = %d, want 2 (operational); stderr=%s", code, stderr)
		}
	})

	t.Run("bad argument shapes are operational errors, never touching a report", func(t *testing.T) {
		cases := []struct {
			name string
			args []string
		}{
			{"no args", nil},
			{"missing --rationale", []string{"spec/demo", "computed-a", "fixed"}},
			{"unknown decision", []string{"spec/demo", "computed-a", "close-enough", "--rationale", "z"}},
			{"too many positionals", []string{"spec/demo", "computed-a", "fixed", "extra"}},
			{"rationale contains a newline", []string{"spec/demo", "computed-a", "fixed", "--rationale", "line one\nline two"}},
			{"rationale contains a control character", []string{"spec/demo", "computed-a", "fixed", "--rationale", "text\twith\ttab"}},
		}
		for _, tc := range cases {
			t.Run(tc.name, func(t *testing.T) {
				root := writeDispositionStoreRoot(t, "demo", buildDispositionFixture(t, livingFindings(), nil))
				path := reportPathFor(root, "demo")
				before := readFile(t, path)

				_, stderr, code := runDispositionBinary(t, bin, root, tc.args...)
				if code != 2 {
					t.Fatalf("exit = %d, want 2 (operational usage error); stderr=%s", code, stderr)
				}
				assertUnchanged(t, path, before)
			})
		}
	})
}

// TestRunDisposition_RationaleValidation is ADJ-52's j-3 fix proof: a
// --rationale carrying a newline or other control character refuses as a
// malformed invocation (exit 2), naming the single-line-bullet constraint
// (align.RenderFindingLine renders a disposition's rationale as one line of
// a markdown bullet; a newline would silently break that invariant with no
// prior argument-shape check catching it — the exact gap the judge found).
// A plain, punctuation-bearing, multi-word rationale must still work
// (exit 0) — the fix must not become an over-broad rejection.
func TestRunDisposition_RationaleValidation(t *testing.T) {
	bin := buildVerdiBinary(t)

	livingFindings := []artifact.Finding{
		{ID: "computed-a", Kind: artifact.FindingComputed, Text: "declared boundary holds"},
	}

	t.Run("newline refuses and names the single-line constraint", func(t *testing.T) {
		root := writeDispositionStoreRoot(t, "demo", buildDispositionFixture(t, livingFindings, nil))
		path := reportPathFor(root, "demo")
		before := readFile(t, path)

		_, stderr, code := runDispositionBinary(t, bin, root, "spec/demo", "computed-a", "fixed", "--rationale", "first line\nsecond line")
		if code != 2 {
			t.Fatalf("exit = %d, want 2 (operational usage error); stderr=%s", code, stderr)
		}
		if !strings.Contains(stderr, "control character") || !strings.Contains(stderr, "single-line") {
			t.Fatalf("stderr = %q, want it to name the control-character/single-line-bullet constraint", stderr)
		}
		assertUnchanged(t, path, before)
	})

	t.Run("a non-newline control character (tab) refuses the same way", func(t *testing.T) {
		root := writeDispositionStoreRoot(t, "demo", buildDispositionFixture(t, livingFindings, nil))
		path := reportPathFor(root, "demo")
		before := readFile(t, path)

		_, stderr, code := runDispositionBinary(t, bin, root, "spec/demo", "computed-a", "fixed", "--rationale", "has\ta\ttab")
		if code != 2 {
			t.Fatalf("exit = %d, want 2 (operational usage error); stderr=%s", code, stderr)
		}
		if !strings.Contains(stderr, "control character") {
			t.Fatalf("stderr = %q, want it to name the control-character constraint", stderr)
		}
		assertUnchanged(t, path, before)
	})

	t.Run("plain multi-word rationale with punctuation still works", func(t *testing.T) {
		root := writeDispositionStoreRoot(t, "demo", buildDispositionFixture(t, livingFindings, nil))
		path := reportPathFor(root, "demo")

		const rationale = "owner-ratified: intentional, tracked separately (see ADR-12) — no server-side change."
		_, stderr, code := runDispositionBinary(t, bin, root, "spec/demo", "computed-a", "fixed", "--rationale", rationale)
		if code != 0 {
			t.Fatalf("exit = %d, want 0 (plain rationale must still work); stderr=%s", code, stderr)
		}
		after := decodeReportFile(t, path)
		f, ok := findingByID(after.Findings, "computed-a")
		if !ok || f.Disposition != artifact.FindingFixed || f.Note != rationale {
			t.Fatalf("computed-a = %+v, want disposition fixed with the given plain rationale", f)
		}
	})
}

// TestRunDisposition_QuotingRationaleDoesNotBrickAnotherFinding is ADJ-52's
// j-2 fix proof: a rationale that quotes another finding's full rendered
// bullet verbatim must never make that OTHER finding's later disposition
// attempt refuse with a false "found N" internal error. Before the fix (a
// raw strings.Count substring lookup over the whole body), the quoted
// finding's line occurred twice in the body text — once as its own real,
// standalone line, once embedded inside the quoting finding's own line —
// permanently bricking the quoted finding's disposition with no sanctioned
// escape hatch, reachable purely through the verb's own documented inputs.
func TestRunDisposition_QuotingRationaleDoesNotBrickAnotherFinding(t *testing.T) {
	bin := buildVerdiBinary(t)

	findings := []artifact.Finding{
		{ID: "finding-a", Kind: artifact.FindingComputed, Text: "a's own claim"},
		{ID: "finding-b", Kind: artifact.FindingJudged, Text: "b's own claim"},
	}
	root := writeDispositionStoreRoot(t, "demo", buildDispositionFixture(t, findings, nil))
	path := reportPathFor(root, "demo")

	// finding-b's CURRENT (undispositioned) rendered line — the exact text
	// a rationale would need to quote verbatim to trigger the brick.
	quotedLine := align.RenderFindingLine(findings[1])

	// Disposition finding-a first, with a rationale that quotes finding-b's
	// full rendered bullet verbatim (embedded inside finding-a's own,
	// longer line — never finding-b's own standalone line).
	_, stderr, code := runDispositionBinary(t, bin, root, "spec/demo", "finding-a", "fixed", "--rationale", "see also: "+quotedLine)
	if code != 0 {
		t.Fatalf("verdi disposition (quoting rationale) exit = %d, want 0; stderr=%s", code, stderr)
	}

	// finding-b's own, still-undispositioned line must STILL be locatable
	// and dispositionable — the fix's whole proof (this would have exited 2
	// with "found 2" against the pre-fix substring-count lookup).
	_, stderr2, code2 := runDispositionBinary(t, bin, root, "spec/demo", "finding-b", "accepted-deviation", "--rationale", "unrelated rationale for b")
	if code2 != 0 {
		t.Fatalf("verdi disposition (finding-b, post-quoting) exit = %d, want 0 (must not brick on the embedded quote); stderr=%s", code2, stderr2)
	}

	after := decodeReportFile(t, path)
	fb, ok := findingByID(after.Findings, "finding-b")
	if !ok || fb.Disposition != artifact.FindingAcceptedDeviation || fb.Note != "unrelated rationale for b" {
		t.Fatalf("finding-b = %+v, want disposition accepted-deviation with the given rationale", fb)
	}
	fa, ok := findingByID(after.Findings, "finding-a")
	if !ok || fa.Disposition != artifact.FindingFixed {
		t.Fatalf("finding-a = %+v, want disposition fixed (unaffected by finding-b's later write)", fa)
	}
}

// TestRunDisposition_UsesAtomicWrite is ADJ-54's j-6 fix proof, structural:
// the write path must replace the report via rename-into-place (a NEW
// underlying file — os.SameFile false against the pre-write file), never a
// plain in-place truncate+write (which keeps the SAME underlying file,
// os.SameFile true) — the portable, observable signature of
// internal/atomicfile.Write's temp-then-rename convention, distinguishing
// it from the pre-fix os.WriteFile. atomicfile.Write's own fsync/crash-
// durability guarantees are already proven by internal/atomicfile's own
// test suite (TestWrite_Happy and neighbors); this proves THIS verb's
// write path actually calls it, closing the truncation risk judged-j-6
// named (a crash/kill/disk-full mid-write leaving a truncated, permanent
// record unrecoverable for content never committed to git).
func TestRunDisposition_UsesAtomicWrite(t *testing.T) {
	bin := buildVerdiBinary(t)
	root := writeDispositionStoreRoot(t, "demo", buildDispositionFixture(t, []artifact.Finding{
		{ID: "computed-a", Kind: artifact.FindingComputed, Text: "declared boundary holds"},
	}, nil))
	path := reportPathFor(root, "demo")

	before, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat before: %v", err)
	}

	_, stderr, code := runDispositionBinary(t, bin, root, "spec/demo", "computed-a", "fixed", "--rationale", "z")
	if code != 0 {
		t.Fatalf("verdi disposition: exit %d, want 0; stderr=%s", code, stderr)
	}

	after, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat after: %v", err)
	}
	if os.SameFile(before, after) {
		t.Fatal("report file identity unchanged across the write — want a NEW underlying file (rename-into-place, internal/atomicfile.Write), not an in-place truncate+rewrite")
	}
}

// TestRunDisposition_ConcurrentModificationRefusesInsteadOfLosingUpdate is
// ADJ-54's j-7 fix proof: a concurrent modification landing between
// runDisposition's initial read and its final write must refuse (exit 2,
// naming the concurrent modification) rather than silently clobber it —
// the exact lost-update scenario judged-j-7 named (two invocations
// targeting DIFFERENT findings of the same report, the second silently
// re-materializing the first's pre-race state while claiming success).
//
// Simulated via dispositionTestInterleave (ADJ-54's own sanctioned
// exception to this file's usual built-binary-only discipline for exactly
// this scenario: "simulate the interleaving... via a test seam or by
// driving the internals" — a real two-PROCESS race would need flaky
// OS-level timing to hit reliably; driving runDisposition directly,
// in-process, makes the race deterministic).
func TestRunDisposition_ConcurrentModificationRefusesInsteadOfLosingUpdate(t *testing.T) {
	findings := []artifact.Finding{
		{ID: "finding-a", Kind: artifact.FindingComputed, Text: "a's own claim"},
		{ID: "finding-b", Kind: artifact.FindingJudged, Text: "b's own claim"},
	}
	root := writeDispositionStoreRoot(t, "demo", buildDispositionFixture(t, findings, nil))
	path := reportPathFor(root, "demo")

	t.Cleanup(func() { dispositionTestInterleave = nil })
	dispositionTestInterleave = func(reportPath string) {
		// Clear the hook FIRST so the inner (concurrent) call below does
		// not recursively retrigger it — the hook must fire exactly once,
		// for the outer call only.
		dispositionTestInterleave = nil
		// The "concurrent" second invocation, landing first — on a
		// DIFFERENT finding than the outer call below, exactly j-7's
		// named scenario.
		if rc := runDisposition(root, "spec/demo", "finding-b", artifact.FindingFixed, "b's concurrent disposition", false, io.Discard, io.Discard); rc != 0 {
			t.Fatalf("test setup: concurrent finding-b disposition failed with rc=%d", rc)
		}
	}

	var stdout, stderr bytes.Buffer
	rc := runDisposition(root, "spec/demo", "finding-a", artifact.FindingAcceptedDeviation, "a's disposition", false, &stdout, &stderr)
	if rc != 2 {
		t.Fatalf("runDisposition (racing finding-a) = %d, want 2 (operational — concurrent modification detected); stdout=%s stderr=%s", rc, stdout.String(), stderr.String())
	}
	if !strings.Contains(stderr.String(), "concurrent") {
		t.Fatalf("stderr = %q, want it to name the concurrent modification", stderr.String())
	}

	// finding-b's concurrent disposition (the "winner", landed first) must
	// survive; finding-a's losing, refused write must not have clobbered
	// it, and finding-a itself must remain undispositioned (the refused
	// write never landed).
	after := decodeReportFile(t, path)
	fb, ok := findingByID(after.Findings, "finding-b")
	if !ok || fb.Disposition != artifact.FindingFixed || fb.Note != "b's concurrent disposition" {
		t.Fatalf("finding-b = %+v, want the concurrent disposition to have survived untouched", fb)
	}
	fa, ok := findingByID(after.Findings, "finding-a")
	if !ok || fa.Dispositioned() {
		t.Fatalf("finding-a = %+v, want it to remain undispositioned (the losing write was refused, never landed)", fa)
	}
}
