package artifact

import "fmt"

const rollupSchema = "verdi.rollup/v1"

// CriterionStatus is one AC's fold outcome (03 §The fold). Precedence is
// total: waived > violated > evidenced > pending > no-signal.
type CriterionStatus string

const (
	CriterionWaived    CriterionStatus = "waived"
	CriterionViolated  CriterionStatus = "violated"
	CriterionEvidenced CriterionStatus = "evidenced"
	CriterionPending   CriterionStatus = "pending"
	CriterionNoSignal  CriterionStatus = "no-signal"
)

var validCriterionStatuses = map[CriterionStatus]bool{
	CriterionWaived:    true,
	CriterionViolated:  true,
	CriterionEvidenced: true,
	CriterionPending:   true,
	CriterionNoSignal:  true,
}

// RollupCriterion is one AC's row in a rollup snapshot.
type RollupCriterion struct {
	ID      string          `json:"id"`
	Text    string          `json:"text"`
	Status  CriterionStatus `json:"status"`
	Summary string          `json:"summary"`
}

// Rollup is schema verdi.rollup/v1 (03 §Closure ritual): the final fold,
// per-AC statuses, evidence summaries, and a digest, generated by
// `verdi close` and frozen alongside the archived spec.
type Rollup struct {
	Schema   string            `json:"schema"`
	Story    string            `json:"story"`
	Ref      string            `json:"ref"`
	Commit   string            `json:"commit"`
	Criteria []RollupCriterion `json:"criteria"`
	Eligible bool              `json:"eligible"`
	Digest   string            `json:"digest"`
}

// DecodeRollup strict-decodes and validates a rollup.json document.
func DecodeRollup(data []byte) (*Rollup, error) {
	var r Rollup
	if err := DecodeStrictJSON(data, &r); err != nil {
		return nil, err
	}
	if err := r.Validate(); err != nil {
		return nil, err
	}
	return &r, nil
}

// Validate checks the schema literal, story (when present) is a
// scheme:key tracker ref, ref is a valid (unpinned) spec ref, commit and
// digest are well-formed, every criterion is individually valid with a
// unique id, and Eligible agrees with 03 §The fold's definition ("every AC
// in {evidenced, waived}") given the decoded criteria.
//
// Story is OPTIONAL (empty string), unlike a story-spec rollup, which
// always carries one: a feature spec's story: tracker ref is itself
// OPTIONAL (R4-I-2, 02 §Kind registry — "an epic/objective tracker ref,
// not a per-story binding"), and spec/true-closure is a real, in-repo
// example of a feature with none at all. A feature rollup with no story
// to publish against is still a valid, honest record of the fold — the
// closure ritual (03 §Closure ritual; cmd/verdi/closefeature.go) still
// writes and archives it, it simply has nowhere to publish (never a
// fabricated tracker ref). When Story is non-empty it is validated exactly
// as before — a malformed non-empty story is still rejected.
func (r Rollup) Validate() error {
	if r.Schema != rollupSchema {
		return fmt.Errorf("artifact: rollup schema %q, want %q", r.Schema, rollupSchema)
	}
	if r.Story != "" && !storyRefRe.MatchString(r.Story) {
		// vocab:identity — strict-decode/schema diagnostic speaking class/field ids
		return fmt.Errorf("artifact: rollup story %q must be scheme:key form", r.Story)
	}
	ref, err := ParseRef(r.Ref)
	if err != nil {
		return fmt.Errorf("artifact: rollup ref: %w", err)
	}
	if ref.Kind != KindSpec {
		return fmt.Errorf("artifact: rollup ref %q must be a spec ref", r.Ref)
	}
	if !commitRe.MatchString(r.Commit) {
		return fmt.Errorf("artifact: rollup commit %q is not a valid sha", r.Commit)
	}
	if !sha256Re.MatchString(r.Digest) {
		return fmt.Errorf("artifact: rollup digest %q is not sha256:<64 hex> form", r.Digest)
	}
	if len(r.Criteria) == 0 {
		return fmt.Errorf("artifact: rollup must list at least one criterion")
	}

	seen := make(map[string]bool, len(r.Criteria))
	allEvidencedOrWaived := true
	for i, c := range r.Criteria {
		if !acIDRe.MatchString(c.ID) {
			return fmt.Errorf("artifact: rollup criteria[%d]: id %q is not a valid ac-<slug> id", i, c.ID)
		}
		if seen[c.ID] {
			return fmt.Errorf("artifact: rollup criteria[%d]: duplicate id %q", i, c.ID)
		}
		seen[c.ID] = true
		if c.Text == "" {
			return fmt.Errorf("artifact: rollup criteria[%d]: text is required", i)
		}
		if !validCriterionStatuses[c.Status] {
			return fmt.Errorf("artifact: rollup criteria[%d]: status %q is not a known status", i, c.Status)
		}
		if c.Status != CriterionEvidenced && c.Status != CriterionWaived {
			allEvidencedOrWaived = false
		}
	}
	if r.Eligible != allEvidencedOrWaived {
		return fmt.Errorf("artifact: rollup eligible=%v disagrees with the fold's definition (every AC in {evidenced, waived}) for the decoded criteria", r.Eligible)
	}
	return nil
}
